<?php

use App\Http\Controllers\Api\AccessControlController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\OwnerController;
use App\Http\Controllers\Api\PropertyController;
use App\Http\Controllers\Api\TenantController;
use App\Http\Controllers\Api\LeaseController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\SystemController;
use App\Http\Controllers\Api\ManagementContractController;
use App\Http\Controllers\Api\BankReconciliationController;
use App\Http\Controllers\Api\ExpenseController;
use App\Http\Controllers\Api\ExpenseUpdateController;
use App\Http\Controllers\Api\MaintenanceController;
use App\Http\Controllers\Api\OwnerSettlementController;
use App\Http\Controllers\Api\AttachmentController;
use App\Http\Controllers\Api\DocumentController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\ReminderController;
use App\Http\Controllers\Api\DashboardController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::middleware('api.auth')->group(function (): void {
        Route::post('/auth/refresh', [AuthController::class, 'refresh']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::get('/dashboard', [DashboardController::class, 'show']);
        Route::get('/roles', [AccessControlController::class, 'roles'])->middleware('permission:settings.roles.view');
        Route::post('/roles', [AccessControlController::class, 'storeRole'])->middleware('permission:settings.roles.manage');
        Route::patch('/roles/{roleId}', [AccessControlController::class, 'updateRole'])->middleware('permission:settings.roles.manage');
        Route::get('/permissions', [AccessControlController::class, 'permissions'])->middleware('permission:settings.roles.view');
        Route::get('/organization', [SystemController::class, 'organization'])->middleware('permission:settings.organization.view');
        Route::patch('/organization', [SystemController::class, 'updateOrganization'])->middleware('permission:settings.organization.manage');
        Route::get('/settings', [SystemController::class, 'organization'])->middleware('permission:settings.organization.view');
        Route::put('/settings', [SystemController::class, 'updateOrganization'])->middleware('permission:settings.organization.manage');
        Route::patch('/settings', [SystemController::class, 'updateOrganization'])->middleware('permission:settings.organization.manage');
        Route::get('/audit-logs', [SystemController::class, 'auditLogs'])->middleware('permission:settings.audit.view');
        Route::get('/users', [UserController::class, 'index'])->middleware('permission:settings.users.view');
        Route::post('/users', [UserController::class, 'store'])->middleware('permission:settings.users.manage');
        Route::patch('/users/{userId}', [UserController::class, 'update'])->middleware('permission:settings.users.manage');
        Route::get('/owners', [OwnerController::class, 'index'])->middleware('permission:owners.view');
        Route::post('/owners', [OwnerController::class, 'store'])->middleware('permission:owners.manage');
        Route::get('/owners/{ownerId}', [OwnerController::class, 'show'])->middleware('permission:owners.view');
        Route::patch('/owners/{ownerId}', [OwnerController::class, 'update'])->middleware('permission:owners.manage');
        Route::get('/owners/{ownerId}/portfolio', [OwnerController::class, 'portfolio'])->middleware('permission:owners.view');
        Route::get('/owners/{ownerId}/bank-accounts', [OwnerController::class, 'bankAccounts'])->middleware('permission:owners.view');
        Route::post('/owners/{ownerId}/bank-accounts', [OwnerController::class, 'storeBankAccount'])->middleware('permission:owners.manage');
        Route::get('/properties', [PropertyController::class, 'index'])->middleware('permission:properties.view');
        Route::post('/properties', [PropertyController::class, 'store'])->middleware('permission:properties.manage');
        Route::get('/properties/{propertyId}', [PropertyController::class, 'show'])->middleware('permission:properties.view');
        Route::get('/properties/{propertyId}/portfolio', [PropertyController::class, 'portfolio'])->middleware('permission:properties.view');
        Route::patch('/properties/{propertyId}', [PropertyController::class, 'update'])->middleware('permission:properties.manage');
        Route::post('/properties/{propertyId}/spaces', [PropertyController::class, 'storeSpace'])->middleware('permission:properties.manage');
        Route::get('/property-spaces', [PropertyController::class, 'spaces'])->middleware('permission:properties.view');
        Route::get('/property-spaces/{spaceId}', [PropertyController::class, 'showSpace'])->middleware('permission:properties.view');
        Route::patch('/property-spaces/{spaceId}', [PropertyController::class, 'updateSpace'])->middleware('permission:properties.manage');
        Route::get('/tenants', [TenantController::class, 'index'])->middleware('permission:tenants.view');
        Route::get('/management-contracts', [ManagementContractController::class, 'index'])->middleware('permission:management_contracts.view');
        Route::post('/management-contracts', [ManagementContractController::class, 'store'])->middleware('permission:management_contracts.manage');
        Route::get('/management-contracts/{contractId}', [ManagementContractController::class, 'show'])->middleware('permission:management_contracts.view');
        Route::patch('/management-contracts/{contractId}', [ManagementContractController::class, 'update'])->middleware('permission:management_contracts.manage');
        Route::post('/management-contracts/{contractId}/activate', [ManagementContractController::class, 'activate'])->middleware('permission:management_contracts.manage');
        Route::post('/tenants', [TenantController::class, 'store'])->middleware('permission:tenants.manage');
        Route::get('/tenants/{tenantId}', [TenantController::class, 'show'])->middleware('permission:tenants.view');
        Route::patch('/tenants/{tenantId}', [TenantController::class, 'update'])->middleware('permission:tenants.manage');
        Route::get('/leases', [LeaseController::class, 'index'])->middleware('permission:leases.view');
        Route::post('/leases', [LeaseController::class, 'store'])->middleware('permission:leases.manage');
        Route::get('/leases/{leaseId}', [LeaseController::class, 'show'])->middleware('permission:leases.view');
        Route::patch('/leases/{leaseId}', [LeaseController::class, 'update'])->middleware('permission:leases.manage');
        Route::post('/leases/{leaseId}/activate', [LeaseController::class, 'activate'])->middleware('permission:leases.manage');
        Route::get('/payments', [PaymentController::class, 'index'])->middleware('permission:payments.view');
        Route::post('/payments', [PaymentController::class, 'store'])->middleware('permission:payments.manage');
        Route::post('/payments/{paymentId}/reverse', [PaymentController::class, 'reverse'])->middleware('permission:payments.reverse');
        Route::get('/receivables', [PaymentController::class, 'openReceivables'])->middleware('permission:receivables.view');
        Route::get('/company-bank-accounts', [BankReconciliationController::class, 'accounts'])->middleware('permission:banking.view');
        Route::get('/bank-transactions', [BankReconciliationController::class, 'transactions'])->middleware('permission:banking.view');
        Route::post('/bank-imports', [BankReconciliationController::class, 'import'])->middleware('permission:banking.import');
        Route::post('/bank-matches', [BankReconciliationController::class, 'match'])->middleware('permission:banking.match');
        Route::delete('/bank-matches/{matchId}', [BankReconciliationController::class, 'unmatch'])->middleware('permission:banking.unmatch');
        Route::get('/vendors', [ExpenseController::class, 'vendors'])->middleware('permission:expenses.view');
        Route::post('/vendors', [ExpenseController::class, 'storeVendor'])->middleware('permission:expenses.manage');
        Route::get('/expenses', [ExpenseController::class, 'index'])->middleware('permission:expenses.view');
        Route::post('/expenses', [ExpenseController::class, 'store'])->middleware('permission:expenses.manage');
        Route::get('/expenses/{expenseId}', [ExpenseController::class, 'show'])->middleware('permission:expenses.view');
        Route::patch('/expenses/{expenseId}', [ExpenseUpdateController::class, 'update'])->middleware('permission:expenses.manage');
        Route::post('/expenses/{expenseId}/decision', [ExpenseController::class, 'decide'])->middleware('permission:expenses.approve');
        Route::get('/maintenance-requests', [MaintenanceController::class, 'index'])->middleware('permission:maintenance.view');
        Route::post('/maintenance-requests', [MaintenanceController::class, 'store'])->middleware('permission:maintenance.manage');
        Route::get('/maintenance-requests/{requestId}', [MaintenanceController::class, 'show'])->middleware('permission:maintenance.view');
        Route::post('/maintenance-requests/{requestId}/decision', [MaintenanceController::class, 'decide'])->middleware('permission:maintenance.approve');
        Route::get('/owner-settlements', [OwnerSettlementController::class, 'index'])->middleware('permission:settlements.view');
        Route::post('/owner-settlements/preview', [OwnerSettlementController::class, 'preview'])->middleware('permission:settlements.manage');
        Route::post('/owner-settlements', [OwnerSettlementController::class, 'store'])->middleware('permission:settlements.manage');
        Route::get('/owner-settlements/{settlementId}', [OwnerSettlementController::class, 'show'])->middleware('permission:settlements.view');
        Route::post('/owner-settlements/{settlementId}/confirm', [OwnerSettlementController::class, 'confirm'])->middleware('permission:settlements.confirm');
        Route::post('/owner-settlements/{settlementId}/transfers', [OwnerSettlementController::class, 'transfer'])->middleware('permission:settlements.transfer');
        Route::post('/attachments/presign', [AttachmentController::class, 'presign'])->middleware('permission:attachments.manage');
        Route::post('/attachments/{attachmentId}/upload', [AttachmentController::class, 'upload'])->middleware('permission:attachments.manage');
        Route::post('/attachments/complete', [AttachmentController::class, 'complete'])->middleware('permission:attachments.manage');
        Route::get('/document-templates', [DocumentController::class, 'templates'])->middleware('permission:documents.view');
        Route::get('/generated-documents', [DocumentController::class, 'documents'])->middleware('permission:documents.view');
        Route::get('/receivables/{receivableId}/demand-letter-context', [DocumentController::class, 'context'])->middleware('permission:receivables.view');
        Route::post('/receivables/{receivableId}/demand-letter/draft', [DocumentController::class, 'draft'])->middleware('permission:documents.generate');
        Route::post('/generated-documents/{documentId}/export', [DocumentController::class, 'export'])->middleware('permission:documents.export');
        Route::post('/collection-follow-ups/{followUpId}/send', [DocumentController::class, 'send'])->middleware('permission:documents.send');
        Route::get('/reports/{reportKey}', [ReportController::class, 'show'])->middleware('permission:reports.view');
        Route::post('/reports/{reportKey}/export', [ReportController::class, 'export'])->middleware('permission:reports.export');
        Route::get('/export-jobs/{jobId}/download', [ReportController::class, 'download'])->middleware('permission:reports.export');
        Route::get('/reminders', [ReminderController::class, 'reminders'])->middleware('permission:reminders.view');
        Route::post('/reminders', [ReminderController::class, 'store'])->middleware('permission:reminders.manage');
        Route::patch('/reminders/{reminderId}', [ReminderController::class, 'update'])->middleware('permission:reminders.manage');
        Route::get('/notifications', [ReminderController::class, 'notifications']);
        Route::post('/notifications/{notificationId}/read', [ReminderController::class, 'read']);
        Route::post('/notifications/read-all', [ReminderController::class, 'readAll']);
    });
});
