'use client'
/* eslint-disable react-hooks/immutability */

import { Building2, CheckCircle2, FileText, MapPin, UserRound, WalletCards, Wrench } from 'lucide-react'
import { useState } from 'react'
import { AppDialog } from './app-dialog'
import { createQuickRecord } from '@/services/quick-create'
import { owners, properties, receivables, tenants, units } from '@/mocks/data'

export type CreateRecordKind = 'owner' | 'property' | 'unit' | 'tenant' | 'lease' | 'payment' | 'expense' | 'managementContract' | 'maintenance'
type Field = { key: string; label: string; required?: boolean; type?: 'text' | 'tel' | 'email' | 'number' | 'date' | 'url'; options?: string[]; section: string; span?: boolean }
type Config = { kind: CreateRecordKind; label: string; description: string; icon: typeof UserRound; fields: Field[] }
const choice = (key: string, label: string, options: string[], section: string, required = false): Field => ({ key, label, options, section, required })
const text = (key: string, label: string, section: string, required = false, type: Field['type'] = 'text'): Field => ({ key, label, section, required, type })
const configs: Config[] = [
  { kind: 'owner', label: 'مالك جديد', description: 'بيانات المالك والتواصل والحساب البنكي.', icon: UserRound, fields: [text('ownerCode', 'رمز المالك', 'بيانات المالك', true), text('fullName', 'الاسم الكامل', 'بيانات المالك', true), text('nationalIdOrIqama', 'رقم الهوية أو الإقامة', 'بيانات المالك', true), text('nationality', 'الجنسية', 'بيانات المالك'), text('mobilePrimary', 'الجوال الأساسي', 'التواصل', true, 'tel'), text('mobileAlternative', 'جوال بديل', 'التواصل', false, 'tel'), text('email', 'البريد الإلكتروني', 'التواصل', false, 'email'), text('city', 'المدينة', 'التواصل', true), text('district', 'الحي', 'التواصل'), text('address', 'العنوان التفصيلي', 'التواصل'), text('bankName', 'اسم البنك', 'الحساب البنكي'), text('accountHolderName', 'اسم صاحب الحساب', 'الحساب البنكي'), text('iban', 'رقم الآيبان', 'الحساب البنكي')] },
  { kind: 'property', label: 'عقار جديد', description: 'عقار مرتبط بمالك مع العنوان والموقع على الخريطة.', icon: Building2, fields: [text('propertyCode', 'رمز العقار', 'بيانات العقار', true), text('propertyName', 'اسم العقار', 'بيانات العقار', true), choice('ownerId', 'المالك', ['بدر عبدالرحمن الصيوان'], 'بيانات العقار', true), choice('propertyType', 'نوع العقار', ['فيلا', 'عمارة سكنية', 'مبنى تجاري', 'شقة مستقلة', 'مزرعة', 'أرض'], 'بيانات العقار', true), text('country', 'الدولة', 'العنوان والموقع', true), text('city', 'المدينة', 'العنوان والموقع', true), text('district', 'الحي', 'العنوان والموقع', true), text('street', 'الشارع', 'العنوان والموقع'), text('fullAddress', 'العنوان التفصيلي', 'العنوان والموقع', true), text('googleMapsUrl', 'رابط موقع الخرائط', 'العنوان والموقع', false, 'url'), text('latitude', 'خط العرض', 'العنوان والموقع', false, 'number'), text('longitude', 'خط الطول', 'العنوان والموقع', false, 'number'), text('deedNumber', 'رقم الصك', 'تفاصيل العقار')] },
  { kind: 'unit', label: 'وحدة / شقة / دور', description: 'جزء قابل للتأجير من عقار قائم.', icon: Building2, fields: [text('unitCode', 'رمز الوحدة', 'بيانات الوحدة', true), choice('propertyId', 'العقار', ['برج الصيوان'], 'بيانات الوحدة', true), text('unitNameOrNumber', 'اسم أو رقم الوحدة', 'بيانات الوحدة', true), choice('unitType', 'نوع الوحدة', ['شقة', 'دور كامل', 'محل', 'مكتب', 'فيلا'], 'بيانات الوحدة', true), text('floor', 'رقم الدور', 'تفاصيل الوحدة', false, 'number'), text('area', 'المساحة (م²)', 'تفاصيل الوحدة', true, 'number'), text('expectedAnnualRent', 'الإيجار السنوي المتوقع', 'الإيجار والخدمات', true, 'number'), text('electricityMeterNumber', 'عداد الكهرباء', 'الإيجار والخدمات'), text('waterMeterNumber', 'عداد المياه', 'الإيجار والخدمات')] },
  { kind: 'tenant', label: 'مستأجر جديد', description: 'بيانات المستأجر الشخصية والتواصل والطوارئ.', icon: UserRound, fields: [text('tenantCode', 'رمز المستأجر', 'بيانات المستأجر', true), text('fullName', 'الاسم الكامل', 'بيانات المستأجر', true), text('nationalIdOrIqama', 'رقم الهوية أو الإقامة', 'بيانات المستأجر', true), text('nationality', 'الجنسية', 'بيانات المستأجر'), text('mobilePrimary', 'رقم الجوال', 'التواصل', true, 'tel'), text('mobileAlternative', 'رقم بديل', 'التواصل', false, 'tel'), text('email', 'البريد الإلكتروني', 'التواصل', false, 'email'), text('emergencyContactName', 'اسم جهة الطوارئ', 'الطوارئ'), text('emergencyContactMobile', 'جوال جهة الطوارئ', 'الطوارئ', false, 'tel')] },
  { kind: 'lease', label: 'عقد إيجار جديد', description: 'أنشئ عقدًا سريعًا؛ يتوفر نموذج مفصل من صفحة عقود الإيجار.', icon: FileText, fields: [text('internalContractNumber', 'رقم العقد الداخلي', 'بيانات العقد', true), text('ejarContractNumber', 'رقم عقد إيجار', 'بيانات العقد'), choice('tenantId', 'المستأجر', ['شركة أبعاد للمقاولات'], 'أطراف العقد', true), choice('propertyId', 'العقار', ['برج الصيوان'], 'أطراف العقد', true), choice('unitId', 'الوحدة / الشقة / الدور', ['مكتب 203', 'شقة 4', 'الدور الأول'], 'أطراف العقد', true), text('startDate', 'تاريخ البداية', 'المدة والتحصيل', true, 'date'), text('endDate', 'تاريخ النهاية', 'المدة والتحصيل', true, 'date'), text('annualRent', 'الإيجار السنوي (ر.س)', 'المدة والتحصيل', true, 'number'), choice('paymentFrequency', 'دورية السداد', ['سنوي', 'نصف سنوي', 'ربع سنوي', 'شهري', 'دفعة واحدة', 'مخصص'], 'المدة والتحصيل', true), text('securityDeposit', 'التأمين (ر.س)', 'المدة والتحصيل', false, 'number')] },
  { kind: 'payment', label: 'تسجيل دفعة', description: 'دفعة مرتبطة باستحقاق محدد.', icon: WalletCards, fields: [choice('receivableId', 'الاستحقاق', ['REC-002 — 30,000 ر.س'], 'بيانات الدفعة', true), text('amount', 'المبلغ', 'بيانات الدفعة', true, 'number'), text('paymentDate', 'تاريخ الدفع', 'بيانات الدفعة', true, 'date'), choice('paymentMethod', 'طريقة الدفع', ['تحويل بنكي', 'نقدي', 'شيك', 'بطاقة'], 'بيانات الدفعة', true), text('transactionReference', 'مرجع العملية', 'بيانات الدفعة')] },
  { kind: 'expense', label: 'مصروف جديد', description: 'مصروف العقار أو الوحدة والمورد والفاتورة والاعتماد.', icon: WalletCards, fields: [choice('propertyId', 'العقار', ['برج الصيوان'], 'بيانات المصروف', true), choice('unitId', 'الوحدة (اختياري)', ['مكتب 203', 'شقة 4', 'الدور الأول'], 'بيانات المصروف'), text('description', 'بيان المصروف', 'بيانات المصروف', true), choice('category', 'الفئة', ['صيانة', 'خدمات', 'تشغيل', 'فواتير', 'أخرى'], 'بيانات المصروف', true), text('amount', 'المبلغ (ر.س)', 'القيمة والاعتماد', true, 'number'), text('expenseDate', 'تاريخ المصروف', 'القيمة والاعتماد', true, 'date'), text('vendorName', 'المورد', 'القيمة والاعتماد'), text('invoiceNumber', 'رقم الفاتورة', 'القيمة والاعتماد'), choice('chargeableToOwner', 'يُحمّل على المالك؟', ['نعم', 'لا'], 'القيمة والاعتماد', true)] },
  { kind: 'managementContract', label: 'عقد إدارة جديد', description: 'عقد إدارة المالك ورسومه ومدته.', icon: FileText, fields: [text('contractNumber', 'رقم عقد الإدارة', 'بيانات العقد', true), choice('ownerId', 'المالك', ['بدر عبدالرحمن الصيوان'], 'بيانات العقد', true), text('startDate', 'تاريخ البداية', 'بيانات العقد', true, 'date'), text('endDate', 'تاريخ النهاية', 'بيانات العقد', true, 'date'), choice('managementFeeMethod', 'طريقة الاحتساب', ['نسبة من التحصيل', 'مبلغ ثابت', 'مخصص'], 'الرسوم والشروط', true), text('managementFeePercentage', 'نسبة الإدارة', 'الرسوم والشروط', false, 'number'), text('paymentTerms', 'شروط الدفع', 'الرسوم والشروط')] },
  { kind: 'maintenance', label: 'طلب صيانة', description: 'طلب تشغيلي مرتبط بعقار ووحدة.', icon: Wrench, fields: [choice('propertyId', 'العقار', ['برج الصيوان'], 'بيانات الطلب', true), choice('unitId', 'الوحدة / الشقة / الدور', ['مكتب 203', 'شقة 4', 'الدور الأول'], 'بيانات الطلب', true), text('title', 'عنوان طلب الصيانة', 'بيانات الطلب', true), choice('priority', 'الأولوية', ['منخفضة', 'متوسطة', 'عالية', 'طارئة'], 'بيانات الطلب', true), text('estimatedCost', 'التكلفة التقديرية', 'التكلفة والاعتماد', false, 'number'), choice('requiresOwnerApproval', 'هل يتطلب اعتماد المالك؟', ['نعم', 'لا'], 'التكلفة والاعتماد', true)] },
]
const blank = (fields: Field[]) => Object.fromEntries(fields.map((field) => [field.key, ''])) as Record<string, string>

export function CreateRecordModal({ open, onClose, initialKind = 'owner' }: { open: boolean; onClose: () => void; initialKind?: CreateRecordKind }) {
  const initial = configs.find((item) => item.kind === initialKind) ?? configs[0]
  const [kind, setKind] = useState<CreateRecordKind>(initial.kind)
  const [values, setValues] = useState<Record<string, string>>(blank(initial.fields))
  const [saved, setSaved] = useState(false)
  const current = configs.find((item) => item.kind === kind) ?? initial
  const optionsFor = (field: Field) => {
    if (field.key === 'ownerId') return owners.map((item) => item.fullName)
    if (field.key === 'propertyId') return properties.map((item) => item.propertyName)
    if (field.key === 'unitId') return units.map((item) => item.unitNameOrNumber)
    if (field.key === 'tenantId') return tenants.map((item) => item.fullName)
    if (field.key === 'receivableId') return receivables.filter((item) => item.remainingAmount > 0).map((item) => `${item.id} — ${item.remainingAmount} ر.س`)
    return field.options
  }
  const select = (item: Config) => { setKind(item.kind); setValues(blank(item.fields)); setSaved(false) }
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (current.fields.some((field) => field.required && !values[field.key]?.trim())) return; await createQuickRecord(kind, values); setSaved(true) }
  let previousSection = ''
  return <AppDialog open={open} onClose={onClose} title="إضافة سجل جديد" description="اختر نوع السجل، ثم أدخل البيانات من دون مغادرة الصفحة."><div className="full-create-modal"><aside>{configs.map((item) => { const Icon = item.icon; return <button type="button" key={item.kind} className={kind === item.kind ? 'selected' : ''} onClick={() => select(item)}><Icon size={18} /><span><b>{item.label}</b><small>{item.description}</small></span></button> })}</aside><form onSubmit={submit}><header><h3>{current.label}</h3><p>{current.description}</p></header>{current.kind === 'property' && <p className="map-note"><MapPin size={16} /> أضف رابط الخريطة أو الإحداثيات لحفظ موقع العقار.</p>}<div className="full-form-grid">{current.fields.map((field) => { const showSection = previousSection !== field.section; previousSection = field.section; const options = optionsFor(field); return <div className={field.span ? 'wide-field' : ''} key={field.key}>{showSection && <h4>{field.section}</h4>}<label>{field.label}{field.required && <em> *</em>}{options ? <select required={field.required} value={values[field.key]} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })}><option value="">اختر {field.label}</option>{options.map((option) => <option value={option} key={option}>{option}</option>)}</select> : <input required={field.required} type={field.type} value={values[field.key]} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} />}</label></div> })}</div>{saved && <p className="modal-success-message"><CheckCircle2 /> تم حفظ السجل محلياً وتوثيق العملية.</p>}<footer><button type="button" className="cancel-button" onClick={onClose}>إلغاء</button><button className="add-button" type="submit">حفظ {current.label}</button></footer></form></div></AppDialog>
}
