'use client'

import Link from 'next/link'
import { Building2, ExternalLink, FileText, MapPin, Phone, UserRound, WalletCards } from 'lucide-react'
import { AppDialog } from '@/components/shared/app-dialog'
import { PortfolioReportActions } from '@/components/shared/portfolio-report-actions'
import { leases, owners, payments, properties, receivables, tenants, units } from '@/mocks/data'

type EntityType = 'owner' | 'property' | 'tenant' | 'unit'
type Props = { open: boolean; entityType: EntityType; entityId?: string; onClose: () => void }
const money = (amount: number) => `${new Intl.NumberFormat('ar-SA').format(amount)} ر.س`

export function EntityPreviewModal({ open, entityType, entityId, onClose }: Props) {
  const entity = entityType === 'owner' ? owners.find((item) => item.id === entityId) : entityType === 'property' ? properties.find((item) => item.id === entityId) : entityType === 'tenant' ? tenants.find((item) => item.id === entityId) : units.find((item) => item.id === entityId)
  if (!entity) return null
  let title = ''; let subtitle = ''; let icon = <Building2 />; let facts: Array<[string, string]> = []; let metrics: Array<[string, string]> = []; let href = ''
  if (entityType === 'owner') { const owner = entity as typeof owners[number]; const propertyItems = properties.filter((item) => item.ownerId === owner.id); const propertyIds = new Set(propertyItems.map((item) => item.id)); const ownerUnits = units.filter((item) => propertyIds.has(item.propertyId)); const relatedLeases = leases.filter((item) => ownerUnits.some((unit) => unit.id === item.unitId)); title = owner.fullName; subtitle = `مالك · ${owner.ownerCode}`; icon = <UserRound />; href = `/owners/${owner.id}`; facts = [['الجوال', owner.mobilePrimary], ['البريد', owner.email ?? '—'], ['المدينة', owner.city], ['البنك', owner.bankAccount.bankName]]; metrics = [['العقارات', String(propertyItems.length)], ['الوحدات', String(ownerUnits.length)], ['العقود', String(relatedLeases.length)], ['المستحق', money(receivables.filter((item) => propertyIds.has(item.propertyId)).reduce((sum, item) => sum + item.remainingAmount, 0))]] }
  if (entityType === 'property') { const property = entity as typeof properties[number]; const propertyUnits = units.filter((item) => item.propertyId === property.id); const unitIds = new Set(propertyUnits.map((item) => item.id)); const contracts = leases.filter((item) => item.propertyId === property.id); title = property.propertyName; subtitle = `${property.propertyCode} · ${property.propertyType}`; icon = <Building2 />; href = `/properties/${property.id}`; facts = [['المالك', owners.find((item) => item.id === property.ownerId)?.fullName ?? '—'], ['الموقع', `${property.city}، ${property.district}`], ['الحالة', property.managementStatus === 'active' ? 'إدارة نشطة' : property.managementStatus], ['رقم الصك', property.deedNumber ?? '—']]; metrics = [['الوحدات', String(propertyUnits.length)], ['المؤجرة', String(propertyUnits.filter((item) => item.status === 'occupied').length)], ['المستأجرون', String(new Set(contracts.map((item) => item.tenantId)).size)], ['الاستحقاقات', money(receivables.filter((item) => item.propertyId === property.id).reduce((sum, item) => sum + item.remainingAmount, 0))]] }
  if (entityType === 'tenant') { const tenant = entity as typeof tenants[number]; const contracts = leases.filter((item) => item.tenantId === tenant.id); const tenantReceivables = receivables.filter((item) => item.tenantId === tenant.id); title = tenant.fullName; subtitle = `مستأجر · ${tenant.tenantCode}`; icon = <UserRound />; href = `/tenants/${tenant.id}`; facts = [['الجوال', tenant.mobilePrimary], ['البريد', tenant.email ?? '—'], ['الهوية', tenant.nationalIdOrIqama], ['الحالة', tenant.status === 'active' ? 'نشط' : tenant.status]]; metrics = [['العقود', String(contracts.length)], ['الاستحقاقات', money(tenantReceivables.reduce((sum, item) => sum + item.originalAmount, 0))], ['المتبقي', money(tenantReceivables.reduce((sum, item) => sum + item.remainingAmount, 0))], ['الدفعات', String(payments.filter((item) => item.tenantId === tenant.id).length)]] }
  if (entityType === 'unit') { const unit = entity as typeof units[number]; const contract = leases.find((item) => item.unitId === unit.id); title = unit.unitNameOrNumber; subtitle = `${unit.unitCode} · ${unit.unitType}`; icon = <Building2 />; href = `/units/${unit.id}`; facts = [['العقار', properties.find((item) => item.id === unit.propertyId)?.propertyName ?? '—'], ['المساحة', `${unit.area} م²`], ['الحالة', unit.status === 'occupied' ? 'مؤجرة' : unit.status === 'vacant' ? 'شاغرة' : unit.status], ['الدور', unit.floor ?? '—']]; metrics = [['الإيجار المتوقع', money(unit.expectedAnnualRent)], ['المستأجر', contract ? tenants.find((item) => item.id === contract.tenantId)?.fullName ?? '—' : 'غير مؤجرة'], ['الاستحقاق', money(receivables.filter((item) => item.unitId === unit.id).reduce((sum, item) => sum + item.remainingAmount, 0))], ['الدفعات', money(payments.filter((item) => item.unitId === unit.id).reduce((sum, item) => sum + item.amount, 0))]] }
  return <AppDialog open={open} onClose={onClose} title="استعراض سريع" description="ملخص السجل وعلاقاته المالية والتشغيلية."><div className="entity-preview"><header className="entity-preview-hero"><span className="entity-preview-icon">{icon}</span><div><h3>{title}</h3><p>{subtitle}</p></div></header><section className="preview-metrics">{metrics.map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</section><section className="preview-facts">{facts.map(([label, value], index) => <div key={label}><span>{index === 0 ? <Phone size={15} /> : index === 1 ? <MapPin size={15} /> : <FileText size={15} />}{label}</span><b>{value}</b></div>)}</section>{(entityType === 'owner' || entityType === 'property') && <PortfolioReportActions entityType={entityType} entityId={entityId ?? ''} />}<footer className="modal-actions"><button className="cancel-button" type="button" onClick={onClose}>إغلاق</button><Link className="add-button" href={href} onClick={onClose}>فتح الملف الكامل <ExternalLink size={16} /></Link></footer></div></AppDialog>
}
