'use client'

import Link from 'next/link'
import { Download, FileBarChart, FileText, Printer } from 'lucide-react'
import { useMemo, useState } from 'react'
import { expenses, owners, payments, properties, receivables, settlements, tenants, units } from '@/mocks/data'

type ReportKind = 'owner-statement' | 'tenant-statement' | 'collections' | 'overdue' | 'upcoming' | 'expenses' | 'occupancy' | 'property'
type Selector = 'owner' | 'tenant' | 'property' | 'none'
type ReportDefinition = { slug: ReportKind; title: string; note: string; selector: Selector; selectorRequired?: boolean }
type ReportResult = { metrics: Array<[string, string]>; headings: string[]; rows: string[][]; description: string }

const reports: ReportDefinition[] = [
  { slug: 'owner-statement', title: 'كشف حساب المالك', note: 'التحصيلات والمصروفات والتسويات والرصيد المستحق لمالك محدد.', selector: 'owner', selectorRequired: true },
  { slug: 'tenant-statement', title: 'كشف حساب المستأجر', note: 'عقود المستأجر واستحقاقاته ودفعاته ورصيده لجهة محددة.', selector: 'tenant', selectorRequired: true },
  { slug: 'collections', title: 'تقرير التحصيلات', note: 'الدفعات المؤكدة خلال فترة محددة، مع إمكانية قصرها على عقار.', selector: 'property' },
  { slug: 'overdue', title: 'تقرير المتأخرات', note: 'الأقساط غير المسددة التي تجاوزت تاريخ الاستحقاق.', selector: 'property' },
  { slug: 'upcoming', title: 'الاستحقاقات القادمة', note: 'الدفعات التي يحل موعدها خلال الفترة المختارة.', selector: 'property' },
  { slug: 'expenses', title: 'المصروفات والصيانة', note: 'مصروفات العقار حسب الفترة، مع توضيح الجهة والمورد.', selector: 'property' },
  { slug: 'occupancy', title: 'تقرير الإشغال', note: 'حالة الإشغال لجميع الوحدات أو لعقار واحد.', selector: 'property' },
  { slug: 'property', title: 'تقرير العقار الشامل', note: 'تشغيل العقار والتحصيلات والاستحقاقات والمصروفات لعقار محدد.', selector: 'property', selectorRequired: true },
]

const money = (amount: number) => `${new Intl.NumberFormat('ar-SA').format(amount)} ر.س`
const today = () => new Date().toISOString().slice(0, 10)
const inDateRange = (date: string, from: string, to: string) => (!from || date >= from) && (!to || date <= to)
const ownerName = (id: string) => owners.find((owner) => owner.id === id)?.fullName ?? '—'
const tenantName = (id: string) => tenants.find((tenant) => tenant.id === id)?.fullName ?? '—'
const propertyName = (id: string) => properties.find((property) => property.id === id)?.propertyName ?? '—'
const unitName = (id: string) => units.find((unit) => unit.id === id)?.unitNameOrNumber ?? '—'

function printReport(title: string, subtitle: string, result: ReportResult) {
  const popup = window.open('', '_blank', 'noopener,noreferrer')
  if (!popup) return
  const safe = (value: string) => value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char] ?? char)
  popup.document.write(`<!doctype html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><title>${safe(title)}</title><style>body{font-family:Tahoma,Arial,sans-serif;padding:32px;color:#173d2a}header{border-bottom:3px solid #178553;padding-bottom:15px}h1{margin:0;font-size:25px}p{color:#66786d}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}.metrics div{background:#f2f8f3;border-radius:8px;padding:11px}.metrics b{display:block;margin-top:5px;color:#087044}table{width:100%;border-collapse:collapse}th{background:#16794e;color:white}th,td{padding:9px;border:1px solid #d6e3d9;text-align:right;font-size:12px}tr:nth-child(even){background:#f7faf7}</style></head><body><header><h1>${safe(title)}</h1><p>${safe(subtitle)} · صادر بتاريخ ${new Intl.DateTimeFormat('ar-SA', { dateStyle: 'long' }).format(new Date())}</p></header><section class="metrics">${result.metrics.map(([label, value]) => `<div>${safe(label)}<b>${safe(value)}</b></div>`).join('')}</section><table><thead><tr>${result.headings.map((heading) => `<th>${safe(heading)}</th>`).join('')}</tr></thead><tbody>${result.rows.map((row) => `<tr>${row.map((cell) => `<td>${safe(cell)}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${result.headings.length}">لا توجد بيانات مطابقة</td></tr>`}</tbody></table></body></html>`)
  popup.document.close(); popup.focus(); popup.print()
}

function reportResult(kind: ReportKind, entityId: string, from: string, to: string): ReportResult {
  const scope = (propertyId: string, tenantId?: string) => (kind === 'owner-statement' ? properties.some((property) => property.id === propertyId && property.ownerId === entityId) : kind === 'tenant-statement' ? tenantId === entityId : !entityId || propertyId === entityId)
  const relevantReceivables = receivables.filter((item) => scope(item.propertyId, item.tenantId) && inDateRange(item.dueDate, from, to))
  const relevantPayments = payments.filter((item) => item.status === 'confirmed' && scope(item.propertyId, item.tenantId) && inDateRange(item.paymentDate, from, to))
  const relevantExpenses = expenses.filter((item) => scope(item.propertyId) && inDateRange(item.expenseDate, from, to))
  const remaining = relevantReceivables.reduce((sum, item) => sum + item.remainingAmount, 0)
  const collected = relevantPayments.reduce((sum, item) => sum + item.amount, 0)
  const overdue = relevantReceivables.filter((item) => item.remainingAmount > 0 && item.dueDate < today())
  const base = { metrics: [] as Array<[string, string]>, headings: [] as string[], rows: [] as string[][], description: '' }
  if (kind === 'owner-statement') {
    const settlement = settlements.find((item) => item.ownerId === entityId)
    return { ...base, description: `كشف حساب المالك: ${ownerName(entityId)}`, metrics: [['المحصلات', money(collected)], ['المتبقي', money(remaining)], ['المتأخرات', money(overdue.reduce((sum, item) => sum + item.remainingAmount, 0))], ['رصيد المالك', money(settlement?.remainingBalance ?? 0)]], headings: ['المستأجر', 'العقار', 'الوحدة', 'الاستحقاق', 'المستحق', 'المدفوع', 'المتبقي', 'الحالة'], rows: relevantReceivables.map((item) => [tenantName(item.tenantId), propertyName(item.propertyId), unitName(item.unitId), item.dueDate, money(item.originalAmount), money(item.paidAmount), money(item.remainingAmount), item.remainingAmount > 0 && item.dueDate < today() ? 'متأخر' : item.status]) }
  }
  if (kind === 'tenant-statement') return { ...base, description: `كشف حساب المستأجر: ${tenantName(entityId)}`, metrics: [['إجمالي الاستحقاقات', money(relevantReceivables.reduce((sum, item) => sum + item.originalAmount, 0))], ['المدفوع', money(collected)], ['الرصيد المتبقي', money(remaining)], ['أقساط متأخرة', String(overdue.length)]], headings: ['العقار', 'الوحدة', 'رقم القسط', 'تاريخ الاستحقاق', 'المستحق', 'المدفوع', 'المتبقي', 'الحالة'], rows: relevantReceivables.map((item) => [propertyName(item.propertyId), unitName(item.unitId), String(item.installmentNumber), item.dueDate, money(item.originalAmount), money(item.paidAmount), money(item.remainingAmount), item.remainingAmount > 0 && item.dueDate < today() ? 'متأخر' : item.status]) }
  if (kind === 'collections') return { ...base, description: entityId ? `تحصيلات العقار: ${propertyName(entityId)}` : 'تحصيلات جميع العقارات', metrics: [['إجمالي المحصل', money(collected)], ['عدد الدفعات', String(relevantPayments.length)], ['المتبقي ضمن النطاق', money(remaining)]], headings: ['رقم الدفعة', 'المستأجر', 'العقار', 'الوحدة', 'التاريخ', 'المبلغ', 'طريقة الدفع'], rows: relevantPayments.map((item) => [item.paymentNumber, tenantName(item.tenantId), propertyName(item.propertyId), unitName(item.unitId), item.paymentDate, money(item.amount), item.paymentMethod]) }
  if (kind === 'overdue') return { ...base, description: entityId ? `متأخرات العقار: ${propertyName(entityId)}` : 'متأخرات جميع العقارات', metrics: [['إجمالي المتأخرات', money(overdue.reduce((sum, item) => sum + item.remainingAmount, 0))], ['الأقساط المتأخرة', String(overdue.length)], ['المستأجرون المتأخرون', String(new Set(overdue.map((item) => item.tenantId)).size)]], headings: ['المستأجر', 'العقار', 'الوحدة', 'تاريخ الاستحقاق', 'المبلغ المتبقي'], rows: overdue.map((item) => [tenantName(item.tenantId), propertyName(item.propertyId), unitName(item.unitId), item.dueDate, money(item.remainingAmount)]) }
  if (kind === 'upcoming') { const upcoming = relevantReceivables.filter((item) => item.remainingAmount > 0 && item.dueDate >= today()); return { ...base, description: entityId ? `استحقاقات العقار: ${propertyName(entityId)}` : 'الاستحقاقات القادمة', metrics: [['إجمالي المستحق', money(upcoming.reduce((sum, item) => sum + item.remainingAmount, 0))], ['عدد الاستحقاقات', String(upcoming.length)]], headings: ['المستأجر', 'العقار', 'الوحدة', 'تاريخ الاستحقاق', 'المبلغ'], rows: upcoming.map((item) => [tenantName(item.tenantId), propertyName(item.propertyId), unitName(item.unitId), item.dueDate, money(item.remainingAmount)]) } }
  if (kind === 'expenses') return { ...base, description: entityId ? `مصروفات العقار: ${propertyName(entityId)}` : 'مصروفات جميع العقارات', metrics: [['إجمالي المصروفات', money(relevantExpenses.reduce((sum, item) => sum + item.amount, 0))], ['عدد البنود', String(relevantExpenses.length)]], headings: ['البيان', 'العقار', 'الوحدة', 'الفئة', 'التاريخ', 'المورد', 'المبلغ'], rows: relevantExpenses.map((item) => [item.description, propertyName(item.propertyId), item.unitId ? unitName(item.unitId) : '—', item.category, item.expenseDate, item.vendorName ?? '—', money(item.amount)]) }
  const scopedUnits = units.filter((unit) => !entityId || unit.propertyId === entityId)
  if (kind === 'occupancy') return { ...base, description: entityId ? `إشغال العقار: ${propertyName(entityId)}` : 'إشغال المحفظة العقارية', metrics: [['إجمالي الوحدات', String(scopedUnits.length)], ['وحدات مؤجرة', String(scopedUnits.filter((unit) => unit.status === 'occupied').length)], ['وحدات شاغرة', String(scopedUnits.filter((unit) => unit.status === 'vacant').length)]], headings: ['العقار', 'الوحدة', 'النوع', 'الحالة', 'الإيجار السنوي'], rows: scopedUnits.map((unit) => [propertyName(unit.propertyId), unit.unitNameOrNumber, unit.unitType, unit.status, money(unit.expectedAnnualRent)]) }
  return { ...base, description: `تقرير العقار: ${propertyName(entityId)}`, metrics: [['الوحدات', String(scopedUnits.length)], ['المحصلات', money(collected)], ['المتبقي', money(remaining)], ['المصروفات', money(relevantExpenses.reduce((sum, item) => sum + item.amount, 0))]], headings: ['الوحدة', 'الحالة', 'الإيجار السنوي', 'المستحق المتبقي'], rows: scopedUnits.map((unit) => [unit.unitNameOrNumber, unit.status, money(unit.expectedAnnualRent), money(relevantReceivables.filter((item) => item.unitId === unit.id).reduce((sum, item) => sum + item.remainingAmount, 0))]) }
}

export function ReportsIndexPage() { return <div className="content reports-page" dir="rtl"><div className="module-title"><div><span className="overline">التقارير والتحليلات</span><h1>التقارير</h1><p>اختر التقرير ثم حدّد الجهة والفترة قبل معاينة البيانات أو تصديرها.</p></div></div><section className="portfolio-report-launch" aria-labelledby="portfolio-report-title"><div className="portfolio-report-launch__icon"><FileBarChart size={25} /></div><div className="portfolio-report-launch__content"><span className="portfolio-report-launch__eyebrow">تقرير موحّد للمحفظة</span><h2 id="portfolio-report-title">ملخص إدارة الأملاك الشامل</h2><p>نظرة تنفيذية للملاك والتحصيلات والتنبيهات، مع ملف تفصيلي مستقل لكل مالك داخل تصدير واحد.</p><div className="portfolio-report-launch__highlights"><span>إحصاءات الملاك</span><span>تنبيهات التأخير</span><span>Excel و PDF</span></div></div><Link className="portfolio-report-launch__cta" href="/reports/management-portfolio"><span>فتح التقرير الشامل</span><FileBarChart size={18} /></Link></section><div className="report-grid">{reports.map((report) => <Link className="card report-card" href={`/reports/${report.slug}`} key={report.slug}><FileText size={20} /><div><h2>{report.title}</h2><p>{report.note}</p></div></Link>)}</div></div> }

export function ReportPage({ kind }: { kind: ReportKind }) {
  const report = reports.find((item) => item.slug === kind) ?? reports[0]
  const [entityId, setEntityId] = useState('')
  const [from, setFrom] = useState('')
  const [to, setTo] = useState('')
  const canGenerate = !report.selectorRequired || Boolean(entityId)
  const options = report.selector === 'owner' ? owners : report.selector === 'tenant' ? tenants : properties
  const selectorLabel = report.selector === 'owner' ? 'المالك' : report.selector === 'tenant' ? 'المستأجر' : 'العقار'
  const selectedName = report.selector === 'owner' ? ownerName(entityId) : report.selector === 'tenant' ? tenantName(entityId) : propertyName(entityId)
  const result = useMemo(() => reportResult(kind, entityId, from, to), [kind, entityId, from, to])
  const exportReport = () => { if (!canGenerate) return; printReport(report.title, result.description, result) }
  return <div className="content reports-page" dir="rtl"><div className="module-title"><div><span className="overline">تقرير تشغيلي</span><h1>{report.title}</h1><p>{report.note}</p></div><div className="report-header-actions"><button className="icon-action" disabled={!canGenerate} onClick={exportReport}><Printer size={17} /><span>طباعة / PDF</span></button><button className="icon-action primary" disabled={!canGenerate} onClick={exportReport}><Download size={17} /><span>تصدير التقرير</span></button></div></div><section className="card report-panel"><div className="report-filters report-filters--context">{report.selector !== 'none' && <label className="report-entity-field"><span>{selectorLabel}{report.selectorRequired && <em> مطلوب</em>}</span><select value={entityId} onChange={(event) => setEntityId(event.target.value)}><option value="">{report.selectorRequired ? `اختر ${selectorLabel} لإصدار التقرير` : `جميع ${report.selector === 'property' ? 'العقارات' : ''}`}</option>{options.map((item) => <option key={item.id} value={item.id}>{'fullName' in item ? item.fullName : item.propertyName}</option>)}</select></label>}<label><span>من تاريخ</span><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label><span>إلى تاريخ</span><input type="date" min={from || undefined} value={to} onChange={(event) => setTo(event.target.value)} /></label></div>{report.selectorRequired && !entityId ? <div className="report-empty-selection"><FileText size={24} /><div><b>حدّد {selectorLabel} أولاً</b><span>لن يتم إنشاء كشف حساب عام؛ اختر الجهة التي تريد مراجعة بياناتها.</span></div></div> : <><div className="report-context-summary"><span>نطاق التقرير</span><b>{entityId ? selectedName : 'جميع العقارات'}</b><small>{from || to ? `الفترة: ${from || 'بداية السجل'} — ${to || 'حتى اليوم'}` : 'الفترة: كامل السجل'}</small></div><div className="report-metrics">{result.metrics.map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className="report-results"><div className="report-results__heading"><div><h2>معاينة النتائج</h2><p>{result.description}</p></div><span>{result.rows.length} سجل</span></div><div className="table-wrap"><table><thead><tr>{result.headings.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{result.rows.map((row, index) => <tr key={`${row.join('-')}-${index}`}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}{!result.rows.length && <tr><td colSpan={result.headings.length}>لا توجد بيانات مطابقة للمعايير المختارة.</td></tr>}</tbody></table></div></div></>}</section></div>
}
