'use client'

import Link from 'next/link'
import { Download, FileText, Printer } from 'lucide-react'
import { expenses, payments, receivables } from '@/mocks/data'

const reports = [{ slug: 'owner-statement', title: 'كشف حساب المالك', note: 'رصيد افتتاحي، تحصيلات، رسوم ومصروفات وتحويلات.' }, { slug: 'tenant-statement', title: 'كشف حساب المستأجر', note: 'العقد والاستحقاقات والدفعات والرصيد.' }, { slug: 'collections', title: 'تقرير التحصيلات', note: 'التحصيلات حسب الفترة والعقار.' }, { slug: 'overdue', title: 'تقرير المتأخرات', note: 'الأقساط المتأخرة وأيام التأخير.' }, { slug: 'upcoming', title: 'الاستحقاقات القادمة', note: 'الاستحقاقات خلال الفترة القادمة.' }, { slug: 'expenses', title: 'المصروفات والصيانة', note: 'المصروفات والتكاليف حسب العقار.' }, { slug: 'occupancy', title: 'تقرير الإشغال', note: 'الوحدات المؤجرة والشاغرة والصيانة.' }, { slug: 'property', title: 'تقرير العقار الشامل', note: 'ملخص تشغيلي ومالي للعقار.' }]
const money = (amount: number) => `${new Intl.NumberFormat('ar-SA').format(amount)} ر.س`
const printReport = (title: string, note: string, metrics: Array<[string, string]>) => { const popup = window.open('', '_blank', 'noopener,noreferrer'); if (!popup) return; popup.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${title}</title><style>body{direction:rtl;font-family:Arial,Tahoma,sans-serif;padding:34px;color:#163d2a}header{border-bottom:3px solid #178553;padding-bottom:16px}h1{margin:0;font-size:26px}p{color:#66786d}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:26px}.metrics div{padding:15px;border:1px solid #dbe9de;border-radius:10px;background:#f5faf6}.metrics b{display:block;margin-top:8px;color:#087044;font-size:19px}footer{border-top:1px solid #dbe9de;margin-top:40px;padding-top:12px;color:#66786d;font-size:12px}</style></head><body><header><h1>${title}</h1><p>${note}</p></header><section class="metrics">${metrics.map(([label, value]) => `<div>${label}<b>${value}</b></div>`).join('')}</section><footer>شركة بدر الصيوان للعقارات · تقرير صادر بتاريخ ${new Intl.DateTimeFormat('ar-SA', { dateStyle: 'long' }).format(new Date())}</footer></body></html>`); popup.document.close(); popup.focus(); popup.print() }

export function ReportsIndexPage() { return <div className="content reports-page" dir="rtl"><div className="module-title"><div><span className="overline">التقارير والتحليلات</span><h1>التقارير</h1><p>تقارير عربية بتنسيق مؤسسي وقابلة للطباعة.</p></div></div><div className="report-grid">{reports.map((report) => <Link className="card report-card" href={`/reports/${report.slug}`} key={report.slug}><FileText size={20} /><div><h2>{report.title}</h2><p>{report.note}</p></div></Link>)}</div></div> }
export function ReportPage({ kind }: { kind: string }) { const report = reports.find((item) => item.slug === kind); const collected = payments.filter((item) => item.status !== 'reversed').reduce((sum, item) => sum + item.amount, 0); const remaining = receivables.reduce((sum, item) => sum + item.remainingAmount, 0); const overdue = receivables.filter((item) => item.status === 'overdue').reduce((sum, item) => sum + item.remainingAmount, 0); const expenseTotal = expenses.reduce((sum, item) => sum + item.amount, 0); const metrics: Array<[string, string]> = [['الدفعات المحصلة', money(collected)], ['المتبقي', money(remaining)], ['المتأخرات', money(overdue)], ['المصروفات', money(expenseTotal)], ['عدد الاستحقاقات', String(receivables.length)], ['تاريخ التقرير', new Intl.DateTimeFormat('ar-SA', { dateStyle: 'medium' }).format(new Date())]]; return <div className="content reports-page" dir="rtl"><div className="module-title"><div><span className="overline">تقرير تفصيلي</span><h1>{report?.title ?? 'تقرير'}</h1><p>{report?.note}</p></div><div className="report-header-actions"><button className="icon-action" onClick={() => printReport(report?.title ?? 'تقرير', report?.note ?? '', metrics)}><Printer size={17} /><span>طباعة / PDF</span></button><button className="icon-action primary" onClick={() => printReport(report?.title ?? 'تقرير', report?.note ?? '', metrics)}><Download size={17} /><span>تصدير التقرير</span></button></div></div><section className="card report-panel"><div className="report-filters"><label>من تاريخ<input type="date" aria-label="من تاريخ" /></label><label>إلى تاريخ<input type="date" aria-label="إلى تاريخ" /></label><button className="icon-action"><FileText size={16} /><span>تطبيق</span></button></div><div className="report-metrics">{metrics.map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div><p className="report-note">يعرض هذا التقرير ملخصًا عربيًا من بيانات النظام الحالية، ويمكن طباعته كـ PDF من زر الطباعة.</p></section></div> }
