'use client'

import Image from 'next/image'
import { AlignmentType, Document, Packer, Paragraph, TextRun } from 'docx'
import { Download, Eye, FileText, Printer, Send } from 'lucide-react'
import { useState } from 'react'
import { AppDialog } from '@/components/shared/app-dialog'
import { documentTemplatesData } from '@/mocks/operations-data'

const companyName = 'شركة بدر الصيوان للعقارات'
const body = 'نفيدكم بموجب سجلات إدارة الأملاك بأن هذه المخاطبة صادرة عن شركة بدر الصيوان للعقارات. يرجى مراجعة البيانات الواردة واتخاذ الإجراء المطلوب خلال المدة المحددة.'
const downloadBlob = (blob: Blob, name: string) => { const link = document.createElement('a'); const url = URL.createObjectURL(blob); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url) }
const paragraph = (text: string, options: { bold?: boolean; size?: number } = {}) => new Paragraph({ alignment: AlignmentType.RIGHT, bidirectional: true, spacing: { after: 180 }, children: [new TextRun({ text, font: 'Arial', rightToLeft: true, bold: options.bold, size: options.size ?? 24 })] })
async function downloadWord(template: string) { const file = new Document({ sections: [{ properties: {}, children: [paragraph(companyName, { bold: true, size: 32 }), paragraph('إدارة الأملاك والتحصيل', { size: 22 }), paragraph(template, { bold: true, size: 30 }), paragraph('السادة/ العميل الكريم،'), paragraph(body), paragraph('وتفضلوا بقبول فائق الاحترام.'), paragraph('التوقيع والختم', { size: 22 })] }] }); downloadBlob(await Packer.toBlob(file), `${template}.docx`) }
function printLetter(template: string) { const content = `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${template}</title><style>body{font-family:Arial,Tahoma,sans-serif;direction:rtl;color:#183d2b;padding:38px 54px;line-height:2}header{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #178553;padding-bottom:16px}header img{width:135px}h1{font-size:25px;text-align:center;margin:38px 0 26px}.letter-meta{color:#5f7367;font-size:13px}main{min-height:410px;font-size:16px}footer{border-top:1px solid #ceded2;padding-top:17px;display:flex;justify-content:space-between;font-size:13px}.stamp{width:140px;text-align:center;border-top:1px dashed #5f7f6b;padding-top:8px}@media print{body{padding:18px}}</style></head><body><header><div><strong>${companyName}</strong><div class="letter-meta">إدارة الأملاك والتحصيل</div></div><img src="${window.location.origin}/logo.png" alt="الشعار"></header><main><h1>${template}</h1><p>السادة/ العميل الكريم،</p><p>${body}</p><p>وتفضلوا بقبول فائق الاحترام.</p></main><footer><span>${companyName}</span><span>تاريخ الإصدار: ${new Intl.DateTimeFormat('ar-SA', { dateStyle: 'long' }).format(new Date())}</span><span class="stamp">التوقيع والختم</span></footer></body></html>`; const windowRef = window.open('', '_blank', 'noopener,noreferrer'); if (!windowRef) return; windowRef.document.write(content); windowRef.document.close(); windowRef.focus(); windowRef.print() }

export function DocumentsPage() { const [active, setActive] = useState<string | null>(null); const [notice, setNotice] = useState(''); const close = () => setActive(null); return <div className="content documents-page" dir="rtl"><div className="module-title"><div><span className="overline">مركز المستندات</span><h1>المستندات والخطابات</h1><p>قوالب مؤسسية عربية جاهزة للمعاينة والطباعة والتصدير.</p></div></div>{notice && <p className="success-message">{notice}</p>}<div className="document-grid">{documentTemplatesData.map((template) => <article className="card document-card" key={template.id}><Image src="/logo.png" alt="بدر الصيوان" width={120} height={45} /><div><h2>{template.name}</h2><p>{template.category} · قالب A4 بهوية الشركة ومنطقة توقيع وختم.</p></div><div className="document-actions"><button className="icon-action" title="معاينة الخطاب" onClick={() => setActive(template.name)}><Eye size={17} /><span>معاينة</span></button><button className="icon-action primary" title="تصدير Word" onClick={() => downloadWord(template.name)}><Download size={17} /><span>Word</span></button></div></article>)}</div><AppDialog open={Boolean(active)} onClose={close} title={active ?? ''} description="معاينة خطاب رسمي قبل الطباعة أو التصدير.">{active && <div className="document-preview" dir="rtl"><header><Image src="/logo.png" alt="الشعار" width={155} height={55} /><div><b>{companyName}</b><span>إدارة الأملاك والتحصيل</span></div></header><main><h1>{active}</h1><p>السادة/ العميل الكريم،</p><p>{body}</p><p>وتفضلوا بقبول فائق الاحترام.</p></main><footer><span>{companyName}</span><span>صفحة 1 من 1</span><div className="signature">التوقيع والختم</div></footer><div className="document-preview-actions"><button className="icon-action" onClick={() => printLetter(active)}><Printer size={17} /><span>طباعة / PDF</span></button><button className="icon-action" onClick={() => downloadWord(active)}><FileText size={17} /><span>Word</span></button><button className="icon-action primary" onClick={() => setNotice(`تم تجهيز ${active} للإرسال التجريبي.`)}><Send size={17} /><span>إرسال</span></button></div></div>}</AppDialog></div> }
