'use client'
import { useEffect, useState } from 'react'
import { listPayments, type Payment } from '@/features/payments/api'
import { createBankMatch, deleteBankMatch, listBankAccounts, listBankTransactions, type BankTransaction, type CompanyBankAccount } from './api'
const money=(v:number)=>`${new Intl.NumberFormat('ar-SA').format(v)} ر.س`
export function BankReconciliationPage(){
 const [accounts,setAccounts]=useState<CompanyBankAccount[]>([]),[transactions,setTransactions]=useState<BankTransaction[]>([]),[payments,setPayments]=useState<Payment[]>([]),[transactionId,setTransactionId]=useState(''),[paymentId,setPaymentId]=useState(''),[amount,setAmount]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true)
 const reload=async()=>{setLoading(true);setError('');try{const[a,t,p]=await Promise.all([listBankAccounts(),listBankTransactions(),listPayments()]);setAccounts(a.items);setTransactions(t.items);setPayments(p.items.filter(x=>x.status==='confirmed'));setTransactionId(x=>x||t.items.find(y=>y.status!=='matched')?.id||'')}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل بيانات المطابقة.')}finally{setLoading(false)}}
 useEffect(()=>{const timer=window.setTimeout(()=>{void reload()},0);return()=>window.clearTimeout(timer)},[]);const transaction=transactions.find(x=>x.id===transactionId)
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!transaction)return;setSaving(true);setError('');try{await createBankMatch({bankTransactionId:transaction.id,paymentId,amount:Number(amount)});setNotice('تمت المطابقة البنكية بنجاح.');setPaymentId('');setAmount('');await reload()}catch(c){setError(c instanceof Error?c.message:'تعذرت المطابقة البنكية.')}finally{setSaving(false)}}
 const unmatch=async(id:string)=>{const reason=window.prompt('سبب فك المطابقة (خمسة أحرف على الأقل):');if(!reason)return;setSaving(true);setError('');try{await deleteBankMatch(id,reason);setNotice('تم فك المطابقة.');await reload()}catch(c){setError(c instanceof Error?c.message:'تعذر فك المطابقة.')}finally{setSaving(false)}}
 if(loading)return <div className="content"><p>جارٍ تحميل المطابقة البنكية…</p></div>
 return <div className="content"><div className="module-title"><div><span className="overline">البنك والتحصيل</span><h1>المطابقة البنكية</h1><p>بيانات فعلية من الخادم؛ لا يمكن تجاوز الرصيد المتبقي.</p></div></div>{error&&<p className="error-message">{error}</p>}{notice&&<p className="success-message">{notice}</p>}<section className="financial-grid">{accounts.map(a=><span key={a.id}>الحساب <b>{a.bankName} · {a.iban}</b></span>)}<span>حركات غير مكتملة <b>{transactions.filter(x=>x.status!=='matched').length}</b></span><span>المتبقي <b>{money(transactions.reduce((s,x)=>s+x.remainingAmount,0))}</b></span></section>{!transactions.length?<section className="card"><p>لا توجد حركات بنك مستوردة بعد.</p></section>:<section className="card entity-form"><label className="full-width">حركة البنك<select value={transactionId} disabled={saving} onChange={e=>{setTransactionId(e.target.value);setPaymentId('');setAmount('')}}>{transactions.map(x=><option key={x.id} value={x.id}>{x.bookedDate} · {x.direction==='inbound'?'وارد':'صادر'} · {money(x.amount)} · {x.externalReference} · {x.status}</option>)}</select></label>{transaction&&<><div className="full-width financial-grid"><span>المطابق سابقاً <b>{money(transaction.matchedAmount)}</b></span><span>المتبقي <b>{money(transaction.remainingAmount)}</b></span></div><form className="full-width entity-form" onSubmit={submit}><label>الدفعة<select required value={paymentId} disabled={saving||transaction.direction!=='inbound'} onChange={e=>{setPaymentId(e.target.value);const p=payments.find(x=>x.id===e.target.value);if(p)setAmount(String(Math.min(p.amount,transaction.remainingAmount)))}}><option value="">اختر الدفعة</option>{payments.map(p=><option key={p.id} value={p.id}>{p.number} · {money(p.amount)} · {p.transactionReference??'دون مرجع'}</option>)}</select></label><label>مبلغ المطابقة<input required type="number" min="0.01" max={transaction.remainingAmount} disabled={saving||transaction.direction!=='inbound'} value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="form-actions"><button className="add-button" type="submit" disabled={saving||transaction.direction!=='inbound'||!paymentId||!Number(amount)}>{saving?'جارٍ الحفظ…':'تأكيد المطابقة'}</button></div></form><div className="full-width">{transaction.matches.map(m=><p key={m.id}>مطابقة: {money(m.amount)} <button type="button" disabled={saving} onClick={()=>void unmatch(m.id)}>فك المطابقة</button></p>)}</div></>}</section>}</div>
}
