'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { listTenants, type Tenant } from '@/features/tenants/api'
import { getLease, updateLease, type LeaseDetail } from './api'

export function LeaseEditPage({ id }: { id: string }) {
  const [lease, setLease] = useState<LeaseDetail>(); const [tenants, setTenants] = useState<Tenant[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState('')
  useEffect(() => { const timer = setTimeout(() => void Promise.all([getLease(id), listTenants()]).then(([lease, tenants]) => { setLease(lease); setTenants(tenants.items.filter(tenant => tenant.status === 'active')) }).catch(error => setError(error instanceof Error ? error.message : 'تعذر تحميل عقد الإيجار.')), 0); return () => clearTimeout(timer) }, [id])
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!lease) return; const form = new FormData(event.currentTarget); setSaving(true); setError(''); setSuccess(''); try { const updated = await updateLease(id, { version: lease.version, internalNumber: String(form.get('internalNumber')), tenantId: String(form.get('tenantId')), startDate: String(form.get('startDate')), endDate: String(form.get('endDate')), annualRent: Number(form.get('annualRent')), totalValue: lease.totalValue, frequency: String(form.get('frequency')), spaces: lease.spaces.map(space => ({ spaceId: space.spaceId, startDate: space.startDate, endDate: space.endDate })), installments: lease.installments.map(installment => ({ dueDate: installment.dueDate, amount: installment.amount })) }); setLease({ ...lease, ...updated }); setSuccess('تم حفظ تعديل المسودة من الخادم.') } catch (error) { setError(error instanceof Error ? error.message : 'تعذر حفظ العقد.') } finally { setSaving(false) } }
  if (!lease) return <div className="content"><p>{error || 'جارٍ تحميل العقد…'}</p></div>
  return <div className="content"><div className="module-title"><div><span className="overline">تعديل عقد إيجار</span><h1>{lease.internalNumber}</h1><p>تعديل المسودة فقط؛ المساحات والأقساط الحالية محفوظة كما هي.</p></div></div><form className="card entity-form" onSubmit={save}><label>رقم العقد<input name="internalNumber" required defaultValue={lease.internalNumber} disabled={saving || lease.status !== 'draft'} /></label><label>المستأجر<select name="tenantId" defaultValue={lease.tenantId} disabled={saving || lease.status !== 'draft'}>{tenants.map(tenant => <option key={tenant.id} value={tenant.id}>{tenant.fullName}</option>)}</select></label><label>تاريخ البداية<input name="startDate" type="date" required defaultValue={lease.startDate} disabled={saving || lease.status !== 'draft'} /></label><label>تاريخ النهاية<input name="endDate" type="date" required defaultValue={lease.endDate} disabled={saving || lease.status !== 'draft'} /></label><label>الإيجار السنوي<input name="annualRent" type="number" min="1" required defaultValue={lease.annualRent} disabled={saving || lease.status !== 'draft'} /></label><label>الدورية<select name="frequency" defaultValue={lease.frequency} disabled={saving || lease.status !== 'draft'}>{['annual', 'semi_annual', 'quarterly', 'monthly', 'one_time', 'custom'].map(frequency => <option key={frequency}>{frequency}</option>)}</select></label><section className="full-width"><h2>المساحات المحفوظة</h2>{lease.spaces.map(space => <p key={space.spaceId}>{space.propertyName} · {space.spaceName} ({space.startDate} — {space.endDate})</p>)}</section><section className="full-width"><h2>الأقساط المحفوظة</h2>{lease.installments.map(installment => <p key={installment.id}>القسط {installment.sequenceNo}: {installment.dueDate} — {installment.amount}</p>)}</section>{error && <p className="error-message full-width">{error}</p>}{success && <p className="success-message full-width">{success}</p>}<div className="form-actions"><Link className="cancel-button" href={`/leases/${id}`}>عودة</Link><button className="add-button" type="submit" disabled={saving || lease.status !== 'draft'}>{saving ? 'جارٍ الحفظ…' : 'حفظ التعديل'}</button></div></form></div>
}
