'use client'

import Link from 'next/link'
import { useState } from 'react'
import { AttachmentUploader, type LocalAttachment } from '@/components/shared/attachment-uploader'
import { owners, settlements } from '@/mocks/data'
import { recordOwnerTransfer } from '@/services/operations'

const money = (value: number) => `${new Intl.NumberFormat('ar-SA').format(value)} ر.س`

export function SettlementsPage() { return <div className="content"><div className="module-title"><div><span className="overline">تسويات الملاك</span><h1>تسويات الملاك</h1><p>احتساب صافي المستحق والتحويلات الجزئية بوضوح.</p></div><Link className="add-button" href="/owner-settlements/new">إنشاء تسوية</Link></div><section className="card table-card"><div className="table-wrap"><table><thead><tr><th>رقم التسوية</th><th>المحصلات</th><th>صافي المستحق</th><th>المحول</th><th>المتبقي</th><th></th></tr></thead><tbody>{settlements.map((item) => <tr key={item.id}><td>{item.settlementNumber}</td><td>{money(item.grossCollections)}</td><td>{money(item.netDueToOwner)}</td><td>{money(item.transferAmount)}</td><td>{money(item.remainingBalance)}</td><td><Link className="cancel-button" href={`/owner-settlements/${item.id}`}>تفاصيل</Link></td></tr>)}</tbody></table></div></section></div> }

export function SettlementDetailPage({ id }: { id: string }) { const settlement = settlements.find((item) => item.id === id); if (!settlement) return <div className="content"><p>التسوية غير موجودة.</p></div>; return <div className="content"><div className="module-title"><div><span className="overline">تفاصيل التسوية</span><h1>{settlement.settlementNumber}</h1><p>فترة التسوية الحالية للمالك.</p></div><Link className="add-button" href={`/owner-settlements/new?settlement=${id}`}>تسجيل تحويل</Link></div><section className="card settlement-breakdown"><div><span>إجمالي المحصلات</span><b>{money(settlement.grossCollections)}</b></div><div><span>− أتعاب الإدارة</span><b>{money(settlement.managementFees)}</b></div><div><span>− مصروفات يتحملها المالك</span><b>{money(settlement.ownerChargeableExpenses)}</b></div><div><span>± تعديلات</span><b>{money(settlement.adjustments)}</b></div><div className="total"><span>= صافي المستحق للمالك</span><b>{money(settlement.netDueToOwner)}</b></div><div><span>− المحول للمالك</span><b>{money(settlement.transferAmount)}</b></div><div className="total"><span>= المتبقي للمالك</span><b>{money(settlement.remainingBalance)}</b></div></section><section className="card"><h2>سجل التحويلات</h2>{settlement.transfers.map((transfer) => <p key={transfer.id}>{money(transfer.amount)} — {transfer.transferDate} — {transfer.transactionReference}</p>)}</section></div> }

export function SettlementFormPage() {
  const [settlementId, setSettlementId] = useState('1')
  const [amount, setAmount] = useState(0)
  const [reference, setReference] = useState('')
  const [attachments, setAttachments] = useState<LocalAttachment[]>([])
  const [notice, setNotice] = useState('')
  const settlement = settlements.find((item) => item.id === settlementId)
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!settlement || amount <= 0 || amount > settlement.remainingBalance || !reference.trim()) return; const updated = await recordOwnerTransfer(settlementId, { amount, transferDate: new Date().toISOString().slice(0, 10), transactionReference: reference }); if (updated) { setNotice(`تم تسجيل التحويل. المتبقي للمالك: ${money(updated.remainingBalance)}`); setAmount(0); setReference('') } }
  return <div className="content"><div className="module-title"><div><span className="overline">تحويل للمالك</span><h1>تسجيل تحويل ضمن تسوية</h1><p>لا يمكن أن يتجاوز التحويل الرصيد المتبقي في التسوية.</p></div></div><form className="card entity-form" onSubmit={submit}><label>التسوية<select value={settlementId} onChange={(event) => setSettlementId(event.target.value)}>{settlements.map((item) => <option key={item.id} value={item.id}>{item.settlementNumber} — {money(item.remainingBalance)}</option>)}</select></label><label>المالك<input readOnly value={owners.find((owner) => owner.id === settlement?.ownerId)?.fullName ?? ''} /></label><label>قيمة التحويل<input type="number" min="1" max={settlement?.remainingBalance} value={amount || ''} onChange={(event) => setAmount(Number(event.target.value))} /></label><label>مرجع العملية<input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="رقم الحوالة أو المرجع البنكي" /></label><div className="full-width financial-grid"><span>صافي المستحق <b>{money(settlement?.netDueToOwner ?? 0)}</b></span><span>المتبقي قبل التحويل <b>{money(settlement?.remainingBalance ?? 0)}</b></span></div><div className="full-width"><AttachmentUploader value={attachments} onChange={setAttachments} entityType="owner_settlement" entityId={settlementId} category="إثبات تحويل" /></div><div className="form-actions"><button className="add-button" type="submit" disabled={!amount || !reference.trim()}>تسجيل التحويل</button></div>{notice && <p className="success-message">{notice}</p>}</form></div>
}
