'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { AppDialog } from '@/components/shared/app-dialog'
import { DataTable } from '@/components/shared/data-table'
import { createPayment, listOpenReceivables, listPayments, reversePayment, type Payment, type Receivable } from './api'

const money = (amount: number) => new Intl.NumberFormat('ar-SA', { style: 'currency', currency: 'SAR' }).format(amount)
const methods: Record<string, string> = { bank_transfer: 'تحويل بنكي', cash: 'نقداً', cheque: 'شيك', card: 'بطاقة', other: 'أخرى' }

export function PaymentsPage() {
  const [payments, setPayments] = useState<Payment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [target, setTarget] = useState<Payment | null>(null); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false)
  const load = () => { setLoading(true); listPayments().then(({ items }) => setPayments(items)).catch(() => setError('تعذر تحميل الدفعات.')).finally(() => setLoading(false)) }
  useEffect(() => { void listPayments().then(({ items }) => setPayments(items)).catch(() => setError('تعذر تحميل الدفعات.')).finally(() => setLoading(false)) }, [])
  const reverse = async () => { if (!target || reason.trim().length < 5) return; setSaving(true); setError(''); try { await reversePayment(target.id, reason); setTarget(null); setReason(''); load() } catch { setError('تعذر عكس الدفعة.'); } finally { setSaving(false) } }
  const confirmed = payments.filter(item => item.status === 'confirmed'); const total = confirmed.reduce((sum, item) => sum + Number(item.amount), 0)
  return <main className="payment-collection page-stack"><section className="module-header collection-header"><div><span className="eyebrow">التحصيل المالي</span><h1>دفعات المستأجرين والتحصيلات</h1><p>دفعات مؤكدة من الخادم مع توزيعها على الاستحقاقات.</p></div><Link href="/payments/new" className="add-button">تسجيل دفعة مستأجر</Link></section><section className="collection-stats"><article className="collection-kpi"><div className="kpi-copy"><span>إجمالي التحصيلات المؤكدة</span><strong>{money(total)}</strong></div></article><article className="collection-kpi"><div className="kpi-copy"><span>دفعات مؤكدة</span><strong>{confirmed.length}</strong></div></article></section>{error && <p role="alert" className="error-message">{error}</p>}{loading ? <p>جارٍ تحميل الدفعات…</p> : <DataTable rows={payments} columns={[{ key: 'number', title: 'رقم الإيصال' }, { key: 'tenantId', title: 'المستأجر' }, { key: 'receiptDate', title: 'تاريخ الاستلام' }, { key: 'amount', title: 'المبلغ', render: value => money(Number(value)) }, { key: 'paymentMethod', title: 'طريقة الدفع', render: value => methods[String(value)] ?? String(value) }, { key: 'status', title: 'الحالة' }, { key: 'id', title: 'الإجراء', render: (_, payment) => payment.status === 'confirmed' ? <button className="table-action danger-action" onClick={() => setTarget(payment)}>عكس الدفعة</button> : '—' }]} />}{<AppDialog open={Boolean(target)} onClose={() => !saving && setTarget(null)} title="عكس دفعة" description="سيعاد فتح الاستحقاقات المرتبطة بعد تسجيل سبب تدقيقي."><label className="reversal-reason-label">سبب العكس<textarea value={reason} disabled={saving} onChange={event => setReason(event.target.value)} /></label><div className="modal-actions"><button className="secondary-button" disabled={saving} onClick={() => setTarget(null)}>إلغاء</button><button className="danger-button" disabled={saving || reason.trim().length < 5} onClick={reverse}>{saving ? 'جارٍ الحفظ…' : 'تأكيد العكس'}</button></div></AppDialog>}</main>
}

export function PaymentFormPage() {
  const [items, setItems] = useState<Receivable[]>([]); const [selectedId, setSelectedId] = useState(''); const [amount, setAmount] = useState(''); const [method, setMethod] = useState('bank_transfer'); const [reference, setReference] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false)
  useEffect(() => { listOpenReceivables().then(({ items }) => { setItems(items); setSelectedId(items[0]?.id ?? '') }).catch(() => setError('تعذر تحميل الاستحقاقات المفتوحة.')).finally(() => setLoading(false)) }, [])
  const selected = items.find(item => item.id === selectedId)
  const save = async () => { if (!selected || !Number(amount) || Number(amount) > Number(selected.balance)) return; setSaving(true); setError(''); try { await createPayment({ tenantId: selected.tenantId, receiptDate: new Date().toISOString().slice(0, 10), paymentMethod: method, amount: Number(amount), currency: 'SAR', transactionReference: reference || undefined, allocations: [{ receivableId: selected.id, amount: Number(amount) }] }); setSaved(true); setAmount(''); const response = await listOpenReceivables(); setItems(response.items); setSelectedId(response.items[0]?.id ?? '') } catch { setError('تعذر تسجيل الدفعة. تحقق من الرصيد والصلاحية ثم أعد المحاولة.') } finally { setSaving(false) } }
  return <main className="page-stack"><section className="module-header"><div><span className="eyebrow">التحصيل المالي</span><h1>تسجيل دفعة مستأجر</h1><p>يتم التحقق من الرصيد والتوزيع داخل معاملة خادم.</p></div></section><section className="card form-card payment-entry-form">{loading ? <p>جارٍ تحميل الاستحقاقات…</p> : <><label>الاستحقاق<select disabled={saving} value={selectedId} onChange={event => { setSelectedId(event.target.value); setAmount(''); setSaved(false) }}><option value="">اختر الاستحقاق</option>{items.map(item => <option key={item.id} value={item.id}>{item.dueDate} — المتبقي {money(Number(item.balance))}</option>)}</select></label>{selected && <p>الرصيد المتبقي: <b>{money(Number(selected.balance))}</b></p>}<label>المبلغ<input disabled={saving} type="number" min="0.01" max={selected?.balance} value={amount} onChange={event => setAmount(event.target.value)} /></label><label>طريقة الدفع<select disabled={saving} value={method} onChange={event => setMethod(event.target.value)}>{Object.entries(methods).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>مرجع العملية<input disabled={saving} value={reference} onChange={event => setReference(event.target.value)} /></label>{error && <p role="alert" className="error-message">{error}</p>}{saved && <p className="form-success">تم تسجيل الدفعة بنجاح.</p>}<button className="primary-button" disabled={saving || !selected || !Number(amount) || Number(amount) > Number(selected.balance)} onClick={save}>{saving ? 'جارٍ الحفظ…' : 'تأكيد تسجيل الدفعة'}</button></>}</section></main>
}
