'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { listOwners, type Owner } from '@/features/owners/api'
import { listProperties, type Property } from '@/features/properties/api'
import { getManagementContract, updateManagementContract, type ManagementContract } from './api'

export function ManagementContractEditPage({ id }: { id: string }) {
  const [contract, setContract] = useState<ManagementContract>(); const [owners, setOwners] = useState<Owner[]>([]); const [properties, setProperties] = useState<Property[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState('')
  useEffect(() => { const timer = setTimeout(() => void Promise.all([getManagementContract(id), listOwners(), listProperties()]).then(([contract, owners, properties]) => { setContract(contract); setOwners(owners.items); setProperties(properties.items) }).catch(error => setError(error instanceof Error ? error.message : 'تعذر تحميل عقد الإدارة.')), 0); return () => clearTimeout(timer) }, [id])
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!contract) return; const form = new FormData(event.currentTarget); setSaving(true); setError(''); setSuccess(''); try { const updated = await updateManagementContract(id, { version: contract.version, contractNumber: String(form.get('contractNumber')), ownerId: String(form.get('ownerId')), startDate: String(form.get('startDate')), endDate: String(form.get('endDate')), feeMethod: String(form.get('feeMethod')), percentRate: form.get('percentRate') ? Number(form.get('percentRate')) : null, fixedAmount: form.get('fixedAmount') ? Number(form.get('fixedAmount')) : null, approvalThreshold: form.get('approvalThreshold') ? Number(form.get('approvalThreshold')) : null, scopes: [{ propertyId: String(form.get('propertyId')) }], services: contract.services, exclusions: contract.exclusions }); setContract(updated); setSuccess('تم حفظ العقد من الخادم.') } catch (error) { setError(error instanceof Error ? error.message : 'تعذر حفظ العقد.') } finally { setSaving(false) } }
  if (!contract) return <div className="content"><p>{error || 'جارٍ تحميل العقد…'}</p></div>
  const ownerProperties = properties.filter(property => property.ownerId === contract.ownerId)
  return <div className="content"><div className="module-title"><div><span className="overline">تعديل عقد إدارة</span><h1>{contract.contractNumber}</h1><p>يستبدل النطاق والخدمات والاستثناءات داخل معاملة واحدة.</p></div></div><form className="card management-form" onSubmit={save}><label>رقم العقد<input name="contractNumber" required defaultValue={contract.contractNumber} disabled={saving || contract.status !== 'draft'} /></label><label>المالك<select name="ownerId" defaultValue={contract.ownerId} disabled={saving || contract.status !== 'draft'}>{owners.map(owner => <option key={owner.id} value={owner.id}>{owner.fullName}</option>)}</select></label><label>العقار ضمن النطاق<select name="propertyId" defaultValue={contract.scopes[0]?.propertyId} disabled={saving || contract.status !== 'draft'}>{ownerProperties.map(property => <option key={property.id} value={property.id}>{property.propertyName}</option>)}</select></label><label>البداية<input name="startDate" type="date" required defaultValue={contract.startDate} disabled={saving || contract.status !== 'draft'} /></label><label>النهاية<input name="endDate" type="date" required defaultValue={contract.endDate} disabled={saving || contract.status !== 'draft'} /></label><label>طريقة الرسوم<select name="feeMethod" defaultValue={contract.feeMethod} disabled={saving || contract.status !== 'draft'}>{['percentage_of_collections', 'fixed', 'hybrid', 'custom'].map(method => <option key={method}>{method}</option>)}</select></label><label>النسبة<input name="percentRate" type="number" min="0" max="100" defaultValue={contract.percentRate ?? ''} disabled={saving || contract.status !== 'draft'} /></label><label>المبلغ الثابت<input name="fixedAmount" type="number" min="0" defaultValue={contract.fixedAmount ?? ''} disabled={saving || contract.status !== 'draft'} /></label><label>حد الموافقة<input name="approvalThreshold" type="number" min="0" defaultValue={contract.approvalThreshold ?? ''} disabled={saving || contract.status !== 'draft'} /></label>{error && <p className="error-message">{error}</p>}{success && <p className="success-message">{success}</p>}<div className="form-actions"><Link className="cancel-button" href="/management-contracts">عودة</Link><button className="add-button" type="submit" disabled={saving || contract.status !== 'draft'}>{saving ? 'جارٍ الحفظ…' : 'حفظ التعديل'}</button></div></form></div>
}
