export type RecordStatus = 'active' | 'inactive' | 'archived' | 'draft' | 'confirmed' | 'cancelled'
export type UnitStatus = 'vacant' | 'occupied' | 'reserved' | 'maintenance' | 'unavailable'
export type LeaseStatus = 'draft' | 'active' | 'expired' | 'terminated' | 'cancelled' | 'renewed'
export type ReceivableStatus = 'upcoming' | 'due_soon' | 'due_today' | 'partially_paid' | 'paid' | 'overdue' | 'cancelled'
export interface OwnerBankAccount { bankName: string; accountHolderName: string; iban: string; accountNumber?: string; swiftCode?: string; bankNotes?: string }
export interface Owner { id: string; ownerCode: string; fullName: string; nationalIdOrIqama: string; mobilePrimary: string; mobileAlternative?: string; email?: string; nationality: string; address?: string; city: string; district?: string; notes?: string; status: RecordStatus; bankAccount: OwnerBankAccount }
export interface PropertyLocation { latitude?: number; longitude?: number; mapUrl?: string; country?: string; city: string; district: string; street?: string; buildingNumber?: string; postalCode?: string; additionalAddress?: string }
export interface Property { id: string; propertyCode: string; propertyName: string; ownerId: string; propertyType: string; city: string; district: string; unitsCount: number; managementStatus: RecordStatus; location?: PropertyLocation; description?: string; deedNumber?: string; electricityAccountNumber?: string; waterAccountNumber?: string }
export interface PropertyUnit { id: string; unitCode: string; propertyId: string; unitNameOrNumber: string; unitType: string; area: number; expectedAnnualRent: number; status: UnitStatus; floor?: string; bedrooms?: number; bathrooms?: number; electricityMeterNumber?: string; waterMeterNumber?: string; notes?: string }
export interface Tenant { id: string; tenantCode: string; fullName: string; nationalIdOrIqama: string; nationality: string; mobilePrimary: string; mobileAlternative?: string; email?: string; employer?: string; occupation?: string; address?: string; city?: string; emergencyContactName?: string; emergencyContactMobile?: string; status: RecordStatus }
export interface LeaseInstallment { installmentNumber: number; dueDate: string; amount: number; notes?: string }
export interface LeaseContract { id: string; internalContractNumber: string; ejarContractNumber?: string; tenantId: string; propertyId: string; unitId: string; startDate: string; endDate: string; annualRent: number; totalContractValue: number; currency: string; paymentFrequency: 'annual' | 'semi_annual' | 'quarterly' | 'monthly' | 'one_time' | 'custom'; status: LeaseStatus; installments: LeaseInstallment[]; securityDeposit?: number; noticePeriodDays?: number; renewalTerms?: string; notes?: string; createdAt?: string; createdBy?: string }
export interface Receivable { id: string; leaseId: string; tenantId: string; propertyId: string; unitId: string; installmentNumber: number; dueDate: string; originalAmount: number; paidAmount: number; remainingAmount: number; status: ReceivableStatus }
export interface Payment { id: string; paymentNumber: string; tenantId: string; leaseId: string; receivableId: string; propertyId: string; unitId: string; amount: number; paymentDate: string; paymentMethod: 'bank_transfer' | 'cash' | 'cheque' | 'card' | 'other'; status: 'confirmed' | 'reversed'; currency?: string; transactionReference?: string; chequeNumber?: string; chequeBank?: string; chequeDate?: string; createdAt?: string; createdBy?: string }
export interface Expense { id: string; propertyId: string; description: string; category: string; amount: number; expenseDate: string; status: RecordStatus; unitId?: string; ownerId?: string; vendorName?: string; invoiceNumber?: string; chargeableToOwner?: boolean; approvalStatus?: 'not_required' | 'pending' | 'approved' | 'rejected'; currency?: string; vatAmount?: number; invoiceStatus?: 'not_received' | 'received' | 'verified'; createdAt?: string; createdBy?: string; approvedAt?: string; approvedBy?: string }
export interface ManagementContract { id: string; contractNumber: string; ownerId: string; startDate: string; endDate: string; status: RecordStatus; managementFeeMethod: string; managementFeePercentage: number; managedPropertyIds?: string[]; serviceScope?: string[]; exclusions?: string[]; paymentTerms?: string; terminationTerms?: string; notes?: string }
export interface MaintenanceRequest { id: string; propertyId: string; unitId: string; title: string; description: string; estimatedCost: number; status: RecordStatus; requiresOwnerApproval: boolean; ownerId?: string; priority?: 'low' | 'medium' | 'high' | 'urgent'; requestedAt?: string; vendorName?: string; actualCost?: number; approvalStatus?: 'not_required' | 'pending' | 'approved' | 'rejected'; completionNotes?: string }
export interface OwnerTransfer { id: string; amount: number; transferDate: string; transactionReference: string; currency?: string; createdAt?: string; createdBy?: string }
export interface OwnerSettlement { id: string; settlementNumber: string; ownerId: string; grossCollections: number; managementFees: number; ownerChargeableExpenses: number; adjustments: number; netDueToOwner: number; previouslyTransferred: number; transferAmount: number; remainingBalance: number; status: RecordStatus; transfers: OwnerTransfer[]; fromDate?: string; toDate?: string; propertyIds?: string[]; paymentIds?: string[]; expenseIds?: string[]; managementFeeRate?: number; currency?: string; createdAt?: string; createdBy?: string }
export interface Attachment { id: string; name: string; category: string; uploadedAt: string; mimeType?: string; size?: number; relatedEntityType?: string; relatedEntityId?: string; uploadedBy?: string; url?: string }
export interface Reminder { id: string; title: string; dueDate: string; status: RecordStatus; type?: 'rent_due' | 'contract_expiry' | 'maintenance' | 'custom'; relatedEntityType?: string; relatedEntityId?: string; reminderDate?: string; recipients?: string[] }
export interface Notification { id: string; title: string; body: string; isRead: boolean; createdAt: string }
export interface User { id: string; fullName: string; roleId: string; status: RecordStatus }
export interface Role { id: string; name: string; permissionIds: string[] }
export interface Permission { id: string; key: string; description: string }
export interface AuditLog { id: string; timestamp: string; user: string; action: string; entity: string; entityId: string; changesSummary: string }
export interface PaymentReversal { id: string; paymentId: string; reason: string; reversedAt: string; reversedBy: string }
export interface MaintenanceApproval { id: string; maintenanceRequestId: string; ownerId: string; status: 'pending' | 'approved' | 'rejected'; requestedAt: string; respondedAt?: string; notes?: string }
export interface CommunicationLog { id: string; relatedEntityType: string; relatedEntityId: string; channel: 'email' | 'sms' | 'whatsapp' | 'system'; subject: string; body: string; sentAt: string; status: 'queued' | 'sent' | 'failed' }
export interface DocumentTemplate { id: string; name: string; category: string; bodyHtml: string; isActive: boolean }
export interface GeneratedDocument { id: string; templateId: string; relatedEntityType: string; relatedEntityId: string; fileName: string; generatedAt: string; status: 'draft' | 'generated' | 'sent' }
