import { expenses, leases, managementContracts, owners, properties, receivables, tenants, units } from '@/mocks/data'
import { maintenanceRequests } from '@/mocks/operations-data'
import { recordPayment } from '@/services/operations'
import { logAudit, persistFrontendData } from '@/services/frontend-store'
import type { Expense, LeaseContract, ManagementContract, Owner, Payment, Property, PropertyUnit, Tenant } from '@/types/domain'

export type QuickRecordKind = 'owner' | 'property' | 'unit' | 'tenant' | 'lease' | 'payment' | 'expense' | 'managementContract' | 'maintenance'
export type QuickValues = Record<string, string>
const id = () => crypto.randomUUID()
const number = (value: string) => Number(value || 0)
const lookup = <T extends { id: string }>(value: string, records: T[], label: (item: T) => string | undefined) => records.find((item) => item.id === value || label(item) === value)?.id ?? value

export async function createQuickRecord(kind: QuickRecordKind, values: QuickValues) {
  if (kind === 'owner') { const record: Owner = { id: id(), ownerCode: values.ownerCode, fullName: values.fullName, nationalIdOrIqama: values.nationalIdOrIqama, nationality: values.nationality, mobilePrimary: values.mobilePrimary, mobileAlternative: values.mobileAlternative || undefined, email: values.email || undefined, city: values.city, district: values.district || undefined, address: values.address || undefined, status: 'active', bankAccount: { bankName: values.bankName, accountHolderName: values.accountHolderName || values.fullName, iban: values.iban } }; owners.push(record); logAudit('إنشاء', 'مالك', record.id, `إضافة المالك ${record.fullName}`); return record }
  if (kind === 'property') { const record: Property = { id: id(), propertyCode: values.propertyCode, propertyName: values.propertyName, ownerId: lookup(values.ownerId, owners, (item) => item.fullName), propertyType: values.propertyType, city: values.city, district: values.district, unitsCount: 0, managementStatus: 'active', deedNumber: values.deedNumber || undefined, location: { country: values.country, city: values.city, district: values.district, street: values.street || undefined, additionalAddress: values.fullAddress, mapUrl: values.googleMapsUrl || undefined, latitude: values.latitude ? number(values.latitude) : undefined, longitude: values.longitude ? number(values.longitude) : undefined } }; properties.push(record); logAudit('إنشاء', 'عقار', record.id, `إضافة العقار ${record.propertyName}`); return record }
  if (kind === 'unit') { const propertyId = lookup(values.propertyId, properties, (item) => item.propertyName); const record: PropertyUnit = { id: id(), unitCode: values.unitCode, propertyId, unitNameOrNumber: values.unitNameOrNumber, unitType: values.unitType, area: number(values.area), expectedAnnualRent: number(values.expectedAnnualRent), status: 'vacant', floor: values.floor || undefined, electricityMeterNumber: values.electricityMeterNumber || undefined, waterMeterNumber: values.waterMeterNumber || undefined }; units.push(record); const property = properties.find((item) => item.id === propertyId); if (property) property.unitsCount += 1; logAudit('إنشاء', 'وحدة', record.id, `إضافة الوحدة ${record.unitNameOrNumber}`); return record }
  if (kind === 'tenant') { const record: Tenant = { id: id(), tenantCode: values.tenantCode, fullName: values.fullName, nationalIdOrIqama: values.nationalIdOrIqama, nationality: values.nationality, mobilePrimary: values.mobilePrimary, mobileAlternative: values.mobileAlternative || undefined, email: values.email || undefined, emergencyContactName: values.emergencyContactName || undefined, emergencyContactMobile: values.emergencyContactMobile || undefined, status: 'active' }; tenants.push(record); logAudit('إنشاء', 'مستأجر', record.id, `إضافة المستأجر ${record.fullName}`); return record }
  if (kind === 'lease') {
    const frequency = ({ 'سنوي': 'annual', 'نصف سنوي': 'semi_annual', 'ربع سنوي': 'quarterly', 'شهري': 'monthly', 'دفعة واحدة': 'one_time', 'مخصص': 'custom' }[values.paymentFrequency] ?? values.paymentFrequency) as LeaseContract['paymentFrequency']
    const tenantId = lookup(values.tenantId, tenants, (item) => item.fullName), propertyId = lookup(values.propertyId, properties, (item) => item.propertyName), leasedSpaceType = (values.leasedSpaceType || 'unit') as LeaseContract['leasedSpaceType'], unitId = leasedSpaceType === 'unit' ? lookup(values.unitId, units, (item) => item.unitNameOrNumber) : ''
    const leasedSpaceId = leasedSpaceType === 'unit' ? unitId : leasedSpaceType === 'whole_property' ? propertyId : values.leasedSpaceId || values.leasedSpaceLabel
    const leasedSpaceLabel = leasedSpaceType === 'unit' ? units.find((item) => item.id === unitId)?.unitNameOrNumber : values.leasedSpaceLabel
    if (!tenants.some((item) => item.id === tenantId) || !properties.some((item) => item.id === propertyId) || (leasedSpaceType === 'unit' && !units.some((item) => item.id === unitId && item.propertyId === propertyId)) || (leasedSpaceType === 'floor' && !leasedSpaceLabel)) throw new Error('تحقق من المستأجر والعقار ونطاق المساحة المؤجرة.')
    if (values.endDate <= values.startDate) throw new Error('تاريخ نهاية العقد يجب أن يكون بعد تاريخ البداية.')
    if (leases.some((lease) => (lease.leasedSpaceId ?? lease.unitId) === leasedSpaceId && lease.status === 'active')) throw new Error('لا يمكن إنشاء عقد نشط: هذه المساحة مؤجرة بعقد قائم.')
    const months = Math.max(1, Math.round((new Date(`${values.endDate}T00:00:00`).getTime() - new Date(`${values.startDate}T00:00:00`).getTime()) / 2629800000))
    const periodsPerYear = { annual: 1, semi_annual: 2, quarterly: 4, monthly: 12, one_time: 1, custom: 1 }[frequency] ?? 1
    const count = frequency === 'one_time' || frequency === 'custom' ? 1 : Math.max(1, Math.ceil(months * periodsPerYear / 12))
    const annualRent = number(values.annualRent), totalContractValue = Math.round(annualRent * months / 12 * 100) / 100
    const start = new Date(`${values.startDate}T00:00:00`), installments = Array.from({ length: count }, (_, index) => { const due = new Date(start); due.setMonth(due.getMonth() + Math.round(index * months / count)); return { installmentNumber: index + 1, dueDate: due.toISOString().slice(0, 10), amount: Math.round((index === count - 1 ? totalContractValue - (totalContractValue / count) * (count - 1) : totalContractValue / count) * 100) / 100 } })
    const record: LeaseContract = { id: id(), internalContractNumber: values.internalContractNumber, ejarContractNumber: values.ejarContractNumber || undefined, tenantId, propertyId, unitId, leasedSpaceType, leasedSpaceId, leasedSpaceLabel, startDate: values.startDate, endDate: values.endDate, annualRent, totalContractValue, currency: 'SAR', paymentFrequency: frequency, status: 'active', securityDeposit: values.securityDeposit ? number(values.securityDeposit) : undefined, noticePeriodDays: values.noticePeriodDays ? number(values.noticePeriodDays) : undefined, installments, createdAt: new Date().toISOString(), createdBy: 'مدير النظام' }
    leases.push(record); receivables.push(...installments.map((item) => ({ id: `REC-${crypto.randomUUID()}`, leaseId: record.id, tenantId, propertyId, unitId, installmentNumber: item.installmentNumber, dueDate: item.dueDate, originalAmount: item.amount, paidAmount: 0, remainingAmount: item.amount, status: 'upcoming' as const }))); const unit = units.find((item) => item.id === unitId); if (unit) unit.status = 'occupied'; logAudit('إنشاء', 'عقد إيجار', record.id, `إنشاء العقد ${record.internalContractNumber} وتوليد ${installments.length} استحقاقاً`); return record
  }
  if (kind === 'payment') { const receivableId = values.receivableId.split(' ')[0]; const receivable = receivables.find((item) => item.id === receivableId); if (!receivable) throw new Error('الاستحقاق غير موجود'); const method = ({ 'تحويل بنكي': 'bank_transfer', 'نقدي': 'cash', 'شيك': 'cheque', 'بطاقة': 'card', 'أخرى': 'other' }[values.paymentMethod] ?? values.paymentMethod) as Payment['paymentMethod']; return recordPayment({ receivableId, amount: number(values.amount), paymentDate: values.paymentDate, paymentMethod: method, transactionReference: values.transactionReference?.trim() || undefined, tenantId: receivable.tenantId, leaseId: receivable.leaseId, propertyId: receivable.propertyId, unitId: receivable.unitId }) }
  if (kind === 'expense') { const record: Expense = { id: id(), propertyId: lookup(values.propertyId, properties, (item) => item.propertyName), unitId: values.unitId ? lookup(values.unitId, units, (item) => item.unitNameOrNumber) : undefined, description: values.description, category: values.category, amount: number(values.amount), expenseDate: values.expenseDate, vendorName: values.vendorName || undefined, invoiceNumber: values.invoiceNumber || undefined, chargeableToOwner: values.chargeableToOwner === 'نعم', approvalStatus: 'not_required', status: 'confirmed', currency: 'SAR', vatAmount: number(values.vatAmount), invoiceStatus: values.invoiceNumber ? 'received' : 'not_received', createdAt: new Date().toISOString(), createdBy: 'مدير النظام' }; expenses.push(record); logAudit('إنشاء', 'مصروف', record.id, `مصروف ${record.description} بقيمة ${record.amount}`); return record }
  if (kind === 'managementContract') { if (values.endDate <= values.startDate) throw new Error('تاريخ نهاية عقد الإدارة يجب أن يكون بعد تاريخ البداية.'); const record: ManagementContract = { id: id(), contractNumber: values.contractNumber, ownerId: lookup(values.ownerId, owners, (item) => item.fullName), startDate: values.startDate, endDate: values.endDate, managementFeeMethod: values.managementFeeMethod, managementFeePercentage: number(values.managementFeePercentage), managedPropertyIds: values.managedPropertyIds ? values.managedPropertyIds.split(',').filter(Boolean) : undefined, serviceScope: values.serviceScope ? values.serviceScope.split(',').filter(Boolean) : undefined, exclusions: values.exclusions ? values.exclusions.split(',').filter(Boolean) : undefined, paymentTerms: values.paymentTerms || undefined, terminationTerms: values.terminationTerms || undefined, notes: values.notes || undefined, status: 'draft' }; managementContracts.push(record); logAudit('إنشاء', 'عقد إدارة', record.id, `إضافة عقد الإدارة ${record.contractNumber}`); return record }
  const record = { id: id(), propertyId: lookup(values.propertyId, properties, (item) => item.propertyName), unitId: lookup(values.unitId, units, (item) => item.unitNameOrNumber), title: values.title, description: values.description || '', estimatedCost: number(values.estimatedCost), status: 'draft' as const, requiresOwnerApproval: values.requiresOwnerApproval === 'نعم', priority: values.priority === 'عالية' ? 'high' as const : 'medium' as const, requestedAt: new Date().toISOString().slice(0, 10), approvalStatus: values.requiresOwnerApproval === 'نعم' ? 'pending' as const : 'not_required' as const }
  maintenanceRequests.push(record); logAudit('إنشاء', 'طلب صيانة', record.id, `طلب صيانة: ${record.title}`); persistFrontendData()
  return record
}
