export type Status = 'active' | 'inactive' | 'draft' | 'pending' | 'paid' | 'overdue' | 'vacant' | 'occupied' | 'reserved' | 'maintenance' | 'unavailable'
export type FeeMethod = 'percentage_of_collections' | 'fixed_annual_amount' | 'percentage_plus_fixed' | 'custom'

export interface Owner { owner_code: string; full_name: string; national_id_or_iqama: string; mobile_primary: string; mobile_alternative: string; email: string; nationality: string; address: string; city: string; district: string; notes: string; status: Status; bank_name: string; account_holder_name: string; iban: string; account_number: string; swift_code: string; bank_notes: string }
export interface ManagementContract { contract_number: string; owner_id: string; start_date: string; end_date: string; signed_date: string; status: Status; notes: string; included_properties: string[]; included_units: string[]; management_fee_method: FeeMethod; management_fee_percentage: number; management_fixed_amount: number; estimated_annual_collections: number; estimated_annual_management_fee: number; services: string[]; exclusions: string[]; custom_terms: string; maintenance_approval_limit: number; attachments: Attachment[]; renewal: string; historical_contracts: string[] }
export interface Property { property_code: string; property_name: string; owner_id: string; property_type: string; description: string; country: string; city: string; district: string; street: string; full_address: string; google_maps_url: string; latitude: number; longitude: number; deed_number: string; land_area: number; built_area: number; floors_count: number; units_count: number; construction_year: number; management_status: Status; management_contract_id: string; management_start_date: string; electricity_account_number: string; water_account_number: string; notes: string }
export interface PropertyUnit { unit_code: string; property_id: string; unit_name_or_number: string; unit_type: string; floor: number; area: number; bedrooms: number; bathrooms: number; living_rooms: number; kitchens: number; entrances: number; furnished: boolean; parking_spaces: number; electricity_meter_number: string; water_meter_number: string; expected_annual_rent: number; status: 'vacant' | 'occupied' | 'reserved' | 'maintenance' | 'unavailable'; availability_date: string; notes: string }
export interface Tenant { tenant_code: string; full_name: string; national_id_or_iqama: string; nationality: string; date_of_birth: string; mobile_primary: string; mobile_alternative: string; email: string; employer: string; occupation: string; emergency_contact_name: string; emergency_contact_mobile: string; address: string; notes: string; status: Status }
export interface LeaseContract { contract_number: string; tenant_id: string; unit_id: string; start_date: string; end_date: string; annual_rent: number; payment_frequency: string; deposit_amount: number; status: Status; installments: Receivable[] }
export interface Receivable { id: string; lease_id: string; tenant_name: string; unit_name: string; due_date: string; amount: number; paid_amount: number; status: 'pending' | 'paid' | 'overdue' }
export interface Payment { id: string; receivable_id: string; amount: number; payment_date: string; method: string; reference: string; notes: string; status: Status }
export interface Expense { id: string; property_id: string; description: string; category: string; amount: number; date: string; status: Status; vendor: string }
export interface MaintenanceRequest { id: string; unit_id: string; title: string; description: string; priority: string; status: Status; estimated_cost: number; created_at: string; timeline: string[] }
export interface OwnerApproval { id: string; subject: string; owner_id: string; amount: number; status: Status; requested_at: string }
export interface OwnerSettlement { id: string; owner_id: string; period: string; collections: number; expenses: number; management_fee: number; net_amount: number; status: Status }
export interface OwnerTransfer { id: string; settlement_id: string; amount: number; transfer_date: string; bank_reference: string; status: Status }
export interface Attachment { id: string; category: 'identity' | 'deed' | 'agency' | 'bank_document' | 'other'; name: string; size: string; uploaded_at: string }
export interface Reminder { id: string; receivable_id: string; channel: string; message: string; scheduled_at: string; status: Status }
export interface Task { id: string; title: string; assignee: string; due_date: string; status: Status }
export interface Notification { id: string; title: string; body: string; read: boolean; created_at: string }
export interface DocumentTemplate { id: string; name: string; type: string; version: string; status: Status }
export interface GeneratedDocument { id: string; template_id: string; name: string; generated_at: string; status: Status }
export interface User { id: string; name: string; email: string; role_id: string; status: Status }
export interface Role { id: string; name: string; permission_ids: string[] }
export interface Permission { id: string; name: string; resource: string; action: string }
export interface AuditLog { id: string; actor: string; action: string; entity: string; created_at: string }

export const owners: Owner[] = [{ owner_code: 'OWN-001', full_name: 'بدر عبدالرحمن الصيوان', national_id_or_iqama: '1012345678', mobile_primary: '0501234567', mobile_alternative: '0115559080', email: 'bader@example.com', nationality: 'سعودي', address: 'حي العليا، شارع الملك فهد', city: 'الرياض', district: 'العليا', notes: 'مالك رئيسي', status: 'active', bank_name: 'مصرف الراجحي', account_holder_name: 'بدر عبدالرحمن الصيوان', iban: 'SA0380000000608010167519', account_number: '608010167519', swift_code: 'RJHISARI', bank_notes: '' }]
export const properties: Property[] = [{ property_code: 'PRP-001', property_name: 'برج الصيوان', owner_id: 'OWN-001', property_type: 'تجاري', description: 'برج إداري في شمال الرياض', country: 'المملكة العربية السعودية', city: 'الرياض', district: 'النخيل', street: 'طريق الملك فهد', full_address: 'برج الصيوان، طريق الملك فهد، الرياض', google_maps_url: 'https://maps.google.com', latitude: 24.774, longitude: 46.738, deed_number: '1234567890', land_area: 2200, built_area: 9800, floors_count: 8, units_count: 36, construction_year: 2020, management_status: 'active', management_contract_id: 'MC-001', management_start_date: '2024-01-01', electricity_account_number: '700123456', water_account_number: '800123456', notes: '' }]
export const units: PropertyUnit[] = [{ unit_code: 'UNT-203', property_id: 'PRP-001', unit_name_or_number: 'مكتب 203', unit_type: 'مكتب', floor: 2, area: 180, bedrooms: 0, bathrooms: 2, living_rooms: 1, kitchens: 1, entrances: 1, furnished: false, parking_spaces: 2, electricity_meter_number: 'M-203', water_meter_number: 'W-203', expected_annual_rent: 222000, status: 'occupied', availability_date: '', notes: '' }]
export const tenants: Tenant[] = [{ tenant_code: 'TEN-001', full_name: 'شركة أبعاد للمقاولات', national_id_or_iqama: '7001234567', nationality: 'سعودي', date_of_birth: '', mobile_primary: '0505551234', mobile_alternative: '', email: 'accounts@abaad.sa', employer: 'شركة أبعاد', occupation: 'مقاولات', emergency_contact_name: 'محمد العتيبي', emergency_contact_mobile: '0551234567', address: 'الرياض', notes: '', status: 'active' }]
export const receivables: Receivable[] = [{ id: 'REC-001', lease_id: 'L-2024-087', tenant_name: 'شركة أبعاد للمقاولات', unit_name: 'برج الصيوان — مكتب 203', due_date: '2024-10-10', amount: 18500, paid_amount: 0, status: 'overdue' }, { id: 'REC-002', lease_id: 'L-2024-091', tenant_name: 'خالد عبدالعزيز العتيبي', unit_name: 'فيلا الياسمين — 4', due_date: '2024-10-12', amount: 24000, paid_amount: 0, status: 'pending' }]
export const attachments: Attachment[] = [{ id: 'ATT-001', category: 'identity', name: 'هوية بدر الصيوان.pdf', size: '1.1 MB', uploaded_at: '2024-09-22' }]
export const navRoutes = ['/dashboard','/owners','/management-contracts','/properties','/units','/tenants','/leases','/receivables','/payments','/expenses','/maintenance','/owner-settlements','/reminders','/notifications','/documents','/reports','/settings']

export function formatMoney(value: number): string { return `${new Intl.NumberFormat('ar-SA').format(value)} ر.س` }
export function routeLabel(pathname: string): string { const segment = pathname.split('/').filter(Boolean).at(-1) ?? 'dashboard'; const labels: Record<string, string> = { dashboard: 'لوحة التحكم', owners: 'الملاك', new: 'إضافة جديد', edit: 'تعديل', 'management-contracts': 'عقود الإدارة', properties: 'العقارات', units: 'الوحدات', tenants: 'المستأجرون', leases: 'عقود الإيجار', receivables: 'الاستحقاقات', payments: 'المدفوعات', expenses: 'المصروفات', maintenance: 'الصيانة', 'owner-settlements': 'تسويات الملاك', reminders: 'التذكيرات', notifications: 'التنبيهات', documents: 'المستندات', reports: 'التقارير', 'owner-statement': 'كشف حساب المالك', 'tenant-statement': 'كشف حساب المستأجر', collections: 'تقرير التحصيلات', overdue: 'تقرير المتأخرات', upcoming: 'الاستحقاقات القادمة', expenses: 'تقرير المصروفات', occupancy: 'تقرير الإشغال', property: 'تقرير العقار', settings: 'الإعدادات' }; return labels[segment] ?? 'لوحة التحكم' }
export function isDetailRoute(pathname: string): boolean { return pathname.split('/').filter(Boolean).some((part) => /^\d+$/.test(part) || /^OWN-|^PRP-|^UNT-|^TEN-|^L-|^MC-/.test(part)) }
export function isCreateRoute(pathname: string): boolean { return pathname.endsWith('/new') }
export function isEditRoute(pathname: string): boolean { return pathname.endsWith('/edit') }
export function validateRequired(values: Record<string, string>, fields: string[]): string[] { return fields.filter((field) => !values[field]?.trim()) }
export const ownerFormFields = ['owner_code','full_name','national_id_or_iqama','mobile_primary','mobile_alternative','email','nationality','address','city','district','notes','bank_name','account_holder_name','iban','account_number','swift_code','bank_notes']
export const propertyFormFields = ['property_code','property_name','owner_id','property_type','country','city','district','street','full_address','deed_number','land_area','built_area','floors_count','units_count','construction_year','management_status','management_contract_id','management_start_date','electricity_account_number','water_account_number','notes']
export const unitFormFields = ['unit_code','property_id','unit_name_or_number','unit_type','floor','area','expected_annual_rent','status','availability_date','notes']
export const tenantFormFields = ['tenant_code','full_name','national_id_or_iqama','nationality','date_of_birth','mobile_primary','mobile_alternative','email','employer','occupation','emergency_contact_name','emergency_contact_mobile','address','notes','status']
export const managementContractFormFields = ['contract_number','owner_id','start_date','end_date','signed_date','status','notes','management_fee_method','management_fee_percentage','management_fixed_amount','estimated_annual_collections','estimated_annual_management_fee','custom_terms','maintenance_approval_limit']
export const reports = ['owner-statement','tenant-statement','collections','overdue','upcoming','expenses','occupancy','property'] as const
