<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\ManagementContract; use App\Models\Owner; use App\Models\Property; use App\Models\PropertySpace; use App\Services\AuditService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;
class ManagementContractController extends Controller {
 public function index(Request $r):JsonResponse{$q=ManagementContract::query()->where('organization_id',$r->attributes->get('organization_id'))->with(['scopes','services','exclusions']);if($r->filled('ownerId'))$q->where('owner_id',$r->input('ownerId'));return $this->success(['items'=>$q->latest()->get()->map(fn($c)=>$this->data($c))]);}
 public function show(Request $r,string $id):JsonResponse{return $this->success($this->data($this->find($r,$id)->load(['scopes','services','exclusions'])));}
 public function store(Request $r):JsonResponse{$d=$this->validated($r,true);$org=$r->attributes->get('organization_id');$contract=DB::transaction(function()use($d,$org){Owner::query()->where('organization_id',$org)->where('status','active')->lockForUpdate()->findOrFail($d['ownerId']);$c=ManagementContract::create(['id'=>(string)Str::uuid(),'organization_id'=>$org,'owner_id'=>$d['ownerId'],'number'=>$d['contractNumber'],'start_date'=>$d['startDate'],'end_date'=>$d['endDate'],'fee_method'=>$d['feeMethod'],'percent_rate'=>$d['percentRate']??null,'fixed_amount'=>$d['fixedAmount']??null,'approval_threshold'=>$d['approvalThreshold']??null]);$this->children($c,$d,$org);return $c->load(['scopes','services','exclusions']);});AuditService::record($org,$r->user()->id,'management_contract.created','management_contract',$contract->id,null,$this->data($contract));return $this->success($this->data($contract),[],201);}
 public function update(Request $r,string $id):JsonResponse{$d=$this->validated($r,false);$org=$r->attributes->get('organization_id');$contract=DB::transaction(function()use($r,$id,$d,$org){$c=ManagementContract::query()->where('organization_id',$org)->with(['scopes','services','exclusions'])->lockForUpdate()->findOrFail($id);if($c->status!=='draft')abort(409,'لا يمكن تعديل عقد إدارة مفعّل أو منتهٍ.');if((int)$c->version!==(int)$d['version'])abort(409,'تم تعديل العقد من مستخدم آخر؛ حدّث الصفحة ثم أعد المحاولة.');$before=$this->data($c);Owner::query()->where('organization_id',$org)->where('status','active')->lockForUpdate()->findOrFail($d['ownerId']);$c->update(['owner_id'=>$d['ownerId'],'number'=>$d['contractNumber'],'start_date'=>$d['startDate'],'end_date'=>$d['endDate'],'fee_method'=>$d['feeMethod'],'percent_rate'=>$d['percentRate']??null,'fixed_amount'=>$d['fixedAmount']??null,'approval_threshold'=>$d['approvalThreshold']??null,'version'=>$c->version+1]);$c->scopes()->delete();$c->services()->delete();$c->exclusions()->delete();$this->children($c,$d,$org);$c=$c->fresh(['scopes','services','exclusions']);AuditService::record($org,$r->user()->id,'management_contract.updated','management_contract',$c->id,$before,$this->data($c));return $c;});return $this->success($this->data($contract));}
 public function activate(Request $r,string $id):JsonResponse{$org=$r->attributes->get('organization_id');$contract=DB::transaction(function()use($r,$id,$org){$c=ManagementContract::query()->where('organization_id',$org)->with('scopes')->lockForUpdate()->findOrFail($id);if($c->status!=='draft'||$c->scopes->isEmpty()||$c->start_date>$c->end_date)abort(409,'لا يمكن تفعيل العقد بحالته الحالية.');$before=['status'=>$c->status];$c->status='active';$c->version++;$c->save();AuditService::record($org,$r->user()->id,'management_contract.activated','management_contract',$c->id,$before,['status'=>'active']);return $c->load(['scopes','services','exclusions']);});return $this->success($this->data($contract));}
 private function children(ManagementContract $c,array $d,string $org):void{foreach($d['scopes'] as $scope){$p=Property::query()->where('organization_id',$org)->where('owner_id',$c->owner_id)->lockForUpdate()->findOrFail($scope['propertyId']);if(!empty($scope['spaceId']))PropertySpace::query()->where('organization_id',$org)->where('property_id',$p->id)->findOrFail($scope['spaceId']);$c->scopes()->create(['id'=>(string)Str::uuid(),'property_id'=>$p->id,'space_id'=>$scope['spaceId']??null]);}foreach($d['services']??[] as $service)$c->services()->create(['id'=>(string)Str::uuid(),'service_code'=>$service['code'],'notes'=>$service['notes']??null]);foreach($d['exclusions']??[] as $exclusion)$c->exclusions()->create(['id'=>(string)Str::uuid(),'exclusion_code'=>$exclusion['code'],'notes'=>$exclusion['notes']??null]);}
 private function validated(Request $r,bool $create):array{return $r->validate(['version'=>$create?['sometimes','integer','min:1']:['required','integer','min:1'],'contractNumber'=>[$create?'required':'required','string','max:80'],'ownerId'=>[$create?'required':'required','uuid'],'startDate'=>[$create?'required':'required','date'],'endDate'=>[$create?'required':'required','date','after:startDate'],'feeMethod'=>[$create?'required':'required','in:percentage_of_collections,fixed,hybrid,custom'],'percentRate'=>['nullable','numeric','min:0','max:100'],'fixedAmount'=>['nullable','numeric','min:0'],'approvalThreshold'=>['nullable','numeric','min:0'],'scopes'=>[$create?'required':'required','array','min:1'],'scopes.*.propertyId'=>['required','uuid'],'scopes.*.spaceId'=>['nullable','uuid'],'services'=>['sometimes','array'],'services.*.code'=>['required','string','max:100'],'services.*.notes'=>['nullable','string'],'exclusions'=>['sometimes','array'],'exclusions.*.code'=>['required','string','max:100'],'exclusions.*.notes'=>['nullable','string']]);}
 private function find(Request $r,string $id):ManagementContract{return ManagementContract::query()->where('organization_id',$r->attributes->get('organization_id'))->findOrFail($id);}
 private function data(ManagementContract $c):array{return ['id'=>$c->id,'contractNumber'=>$c->number,'ownerId'=>$c->owner_id,'startDate'=>$c->start_date,'endDate'=>$c->end_date,'feeMethod'=>$c->fee_method,'percentRate'=>$c->percent_rate,'fixedAmount'=>$c->fixed_amount,'approvalThreshold'=>$c->approval_threshold,'status'=>$c->status,'version'=>$c->version,'scopes'=>$c->scopes->map(fn($s)=>['propertyId'=>$s->property_id,'spaceId'=>$s->space_id])->values(),'services'=>$c->services->map(fn($s)=>['code'=>$s->service_code,'notes'=>$s->notes])->values(),'exclusions'=>$c->exclusions->map(fn($s)=>['code'=>$s->exclusion_code,'notes'=>$s->notes])->values()];}
}
