<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\Owner; use App\Models\Property; use App\Models\PropertySpace; use App\Services\AuditService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;
class PropertyController extends Controller {
 public function index(Request $r):JsonResponse{$q=Property::query()->where('organization_id',$r->attributes->get('organization_id'))->with('owner:id,full_name');if($r->filled('ownerId'))$q->where('owner_id',$r->input('ownerId'));return $this->success(['items'=>$q->orderBy('name')->get()->map(fn($p)=>$this->property($p))]);}
 public function show(Request $r,string $id):JsonResponse{return $this->success($this->property($this->find($r,$id)->load('spaces')));}
 public function portfolio(Request $r,string $id):JsonResponse{$p=$this->find($r,$id)->load('spaces','owner:id,full_name');return $this->success(['property'=>$this->property($p),'spaces'=>$p->spaces->map(fn($s)=>$this->space($s))->values(),'leases'=>[],'receivables'=>[],'expenses'=>[],'maintenance'=>[]]);}
 public function spaces(Request $r):JsonResponse{$q=PropertySpace::query()->where('organization_id',$r->attributes->get('organization_id'));if($r->filled('type'))$q->where('space_type',$r->input('type'));if($r->filled('propertyId'))$q->where('property_id',$r->input('propertyId'));return $this->success(['items'=>$q->orderBy('code')->get()->map(fn($s)=>$this->space($s))]);}
 public function showSpace(Request $r,string $id):JsonResponse{return $this->success($this->space(PropertySpace::query()->where('organization_id',$r->attributes->get('organization_id'))->findOrFail($id)));}
 public function store(Request $r):JsonResponse{$d=$r->validate(['propertyCode'=>['required','string','max:50'],'propertyName'=>['required','string','max:200'],'ownerId'=>['required','uuid'],'propertyType'=>['required','string','max:80'],'city'=>['required','string','max:100'],'district'=>['required','string','max:100'],'deedNumber'=>['nullable','string','max:100'],'address'=>['nullable','array']]);$org=$r->attributes->get('organization_id');$p=DB::transaction(function()use($d,$org){Owner::query()->where('organization_id',$org)->where('status','active')->lockForUpdate()->findOrFail($d['ownerId']);return Property::create(['id'=>(string)Str::uuid(),'organization_id'=>$org,'owner_id'=>$d['ownerId'],'code'=>$d['propertyCode'],'name'=>$d['propertyName'],'property_type'=>$d['propertyType'],'city'=>$d['city'],'district'=>$d['district'],'deed_number'=>$d['deedNumber']??null,'address'=>$d['address']??null]);});AuditService::record($org,$r->user()->id,'property.created','property',$p->id,null,$this->property($p));return $this->success($this->property($p),[],201);}
 public function update(Request $r,string $id):JsonResponse{$d=$r->validate(['propertyName'=>['sometimes','string','max:200'],'propertyType'=>['sometimes','string','max:80'],'city'=>['sometimes','string','max:100'],'district'=>['sometimes','string','max:100'],'deedNumber'=>['nullable','string','max:100'],'status'=>['sometimes','in:active,inactive,archived'],'version'=>['required','integer','min:1']]);$org=$r->attributes->get('organization_id');$p=DB::transaction(function()use($r,$id,$d,$org){$p=$this->find($r,$id,true);if($p->version!==$d['version'])abort(409,'تم تعديل العقار من مستخدم آخر.');$before=$this->property($p);$p->fill(['name'=>$d['propertyName']??$p->name,'property_type'=>$d['propertyType']??$p->property_type,'city'=>$d['city']??$p->city,'district'=>$d['district']??$p->district,'deed_number'=>$d['deedNumber']??$p->deed_number,'status'=>$d['status']??$p->status]);$p->version++;$p->save();AuditService::record($org,$r->user()->id,'property.updated','property',$p->id,$before,$this->property($p));return $p;});return $this->success($this->property($p));}
 public function storeSpace(Request $r,string $propertyId):JsonResponse{$d=$r->validate(['unitCode'=>['required','string','max:50'],'unitNameOrNumber'=>['required','string','max:200'],'unitType'=>['required','in:unit,floor,whole_property'],'floor'=>['nullable','string','max:50'],'area'=>['nullable','numeric','min:0'],'expectedAnnualRent'=>['nullable','numeric','min:0'],'status'=>['sometimes','in:active,inactive,maintenance']]);$org=$r->attributes->get('organization_id');$s=DB::transaction(function()use($r,$propertyId,$d,$org){$p=$this->find($r,$propertyId,true);return PropertySpace::create(['id'=>(string)Str::uuid(),'organization_id'=>$org,'property_id'=>$p->id,'code'=>$d['unitCode'],'name'=>$d['unitNameOrNumber'],'space_type'=>$d['unitType'],'floor'=>$d['floor']??null,'area'=>$d['area']??null,'expected_annual_rent'=>$d['expectedAnnualRent']??null,'status'=>$d['status']??'active']);});AuditService::record($org,$r->user()->id,'property_space.created','property_space',$s->id,null,$this->space($s));return $this->success($this->space($s),[],201);}
 public function updateSpace(Request $r,string $id):JsonResponse{$d=$r->validate(['unitNameOrNumber'=>['sometimes','string','max:200'],'floor'=>['nullable','string','max:50'],'area'=>['nullable','numeric','min:0'],'expectedAnnualRent'=>['nullable','numeric','min:0'],'status'=>['sometimes','in:active,inactive,archived,maintenance'],'version'=>['required','integer','min:1']]);$org=$r->attributes->get('organization_id');$s=DB::transaction(function()use($r,$id,$d,$org){$s=PropertySpace::query()->where('organization_id',$org)->lockForUpdate()->findOrFail($id);if($s->version!==$d['version'])abort(409,'تم تعديل المساحة من مستخدم آخر.');$before=$this->space($s);$s->fill(['name'=>$d['unitNameOrNumber']??$s->name,'floor'=>$d['floor']??$s->floor,'area'=>$d['area']??$s->area,'expected_annual_rent'=>$d['expectedAnnualRent']??$s->expected_annual_rent,'status'=>$d['status']??$s->status]);$s->version++;$s->save();AuditService::record($org,$r->user()->id,'property_space.updated','property_space',$s->id,$before,$this->space($s));return $s;});return $this->success($this->space($s));}
 private function find(Request $r,string $id,bool $lock=false):Property{$q=Property::query()->where('organization_id',$r->attributes->get('organization_id'));if($lock)$q->lockForUpdate();return $q->findOrFail($id);} private function property(Property $p):array{return ['id'=>$p->id,'propertyCode'=>$p->code,'propertyName'=>$p->name,'ownerId'=>$p->owner_id,'ownerName'=>$p->owner?->full_name,'propertyType'=>$p->property_type,'city'=>$p->city,'district'=>$p->district,'deedNumber'=>$p->deed_number,'status'=>$p->status,'version'=>$p->version,'spaces'=>$p->relationLoaded('spaces')?$p->spaces->map(fn($s)=>$this->space($s))->values():[]];} private function space(PropertySpace $s):array{return ['id'=>$s->id,'propertyId'=>$s->property_id,'unitCode'=>$s->code,'unitNameOrNumber'=>$s->name,'unitType'=>$s->space_type,'floor'=>$s->floor,'area'=>$s->area,'expectedAnnualRent'=>$s->expected_annual_rent,'status'=>$s->status,'version'=>$s->version];}
}
