'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { getExpense, updateExpense, type Expense } from './api'
import { listProperties, type Property } from '@/features/properties/api'

export function ExpenseEditPage({ id }: { id: string }) {
  const [expense, setExpense] = useState<Expense>(); const [properties, setProperties] = useState<Property[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState('')
  useEffect(() => { const timer = setTimeout(() => void Promise.all([getExpense(id), listProperties()]).then(([expense, properties]) => { setExpense(expense); setProperties(properties.items) }).catch(error => setError(error instanceof Error ? error.message : 'تعذر تحميل المصروف.')), 0); return () => clearTimeout(timer) }, [id])
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!expense) return; const form = new FormData(event.currentTarget); setSaving(true); setError(''); setSuccess(''); try { const updated = await updateExpense(id, { version: expense.version, propertyId: String(form.get('propertyId')), vendorName: String(form.get('vendorName') || ''), description: String(form.get('description')), category: String(form.get('category')), netAmount: Number(form.get('netAmount')), vatAmount: Number(form.get('vatAmount')), expenseDate: String(form.get('expenseDate')), chargeableToOwner: form.get('chargeableToOwner') === 'on' }); setExpense(updated); setSuccess('تم حفظ التعديل من الخادم.') } catch (error) { setError(error instanceof Error ? error.message : 'تعذر حفظ المصروف.') } finally { setSaving(false) } }
  if (!expense) return <div className="content"><p>{error || 'جارٍ تحميل المصروف…'}</p></div>
  return <div className="content"><div className="module-title"><div><span className="overline">تعديل مصروف</span><h1>{expense.description}</h1><p>لا يمكن تعديل المصروف المؤكد أو الملغى.</p></div></div><form className="card entity-form" onSubmit={save}><label>العقار<select name="propertyId" defaultValue={expense.propertyId} disabled={saving || expense.status !== 'draft'}>{properties.map(property => <option key={property.id} value={property.id}>{property.propertyName}</option>)}</select></label><label>المورد<input name="vendorName" defaultValue={expense.vendorName ?? ''} disabled={saving || expense.status !== 'draft'} /></label><label>الفئة<input name="category" required defaultValue={expense.category} disabled={saving || expense.status !== 'draft'} /></label><label>الصافي<input name="netAmount" type="number" min="0" step="0.01" required defaultValue={expense.netAmount} disabled={saving || expense.status !== 'draft'} /></label><label>الضريبة<input name="vatAmount" type="number" min="0" step="0.01" required defaultValue={expense.vatAmount} disabled={saving || expense.status !== 'draft'} /></label><label>التاريخ<input name="expenseDate" type="date" required defaultValue={expense.expenseDate} disabled={saving || expense.status !== 'draft'} /></label><label className="checkbox"><input name="chargeableToOwner" type="checkbox" defaultChecked={expense.chargeableToOwner} disabled={saving || expense.status !== 'draft'} /> يحمل على المالك</label><label className="full-width">البيان<textarea name="description" required defaultValue={expense.description} disabled={saving || expense.status !== 'draft'} /></label>{error && <p className="error-message full-width">{error}</p>}{success && <p className="success-message full-width">{success}</p>}<div className="form-actions"><Link className="cancel-button" href="/expenses">عودة</Link><button className="add-button" type="submit" disabled={saving || expense.status !== 'draft'}>{saving ? 'جارٍ الحفظ…' : 'حفظ التعديل'}</button></div></form></div>
}
