import { z } from 'zod'
const required = (label: string) => z.string().min(1, `حقل ${label} مطلوب`)
export const ownerSchema = z.object({ fullName: required('اسم المالك'), mobilePrimary: z.string().regex(/^05\d{8}$/, 'رقم الجوال غير صحيح'), nationalIdOrIqama: required('رقم الهوية'), city: required('المدينة') })
export const managementContractSchema = z.object({ contractNumber: required('رقم العقد'), ownerId: required('المالك'), startDate: required('تاريخ البداية'), endDate: required('تاريخ النهاية') }).refine((value) => value.endDate >= value.startDate, { message: 'تاريخ النهاية يجب أن يكون بعد البداية', path: ['endDate'] })
export const propertySchema = z.object({ propertyName: required('اسم العقار'), ownerId: required('المالك'), city: required('المدينة') })
export const unitSchema = z.object({ unitNameOrNumber: required('رقم الوحدة'), propertyId: required('العقار'), expectedAnnualRent: z.coerce.number().positive('الإيجار يجب أن يكون أكبر من صفر') })
export const tenantSchema = z.object({ fullName: required('اسم المستأجر'), mobilePrimary: z.string().regex(/^05\d{8}$/, 'رقم الجوال غير صحيح'), nationalIdOrIqama: required('رقم الهوية') })
export const leaseSchema = z.object({ tenantId: required('المستأجر'), unitId: required('الوحدة'), startDate: required('تاريخ البداية'), endDate: required('تاريخ النهاية'), totalContractValue: z.coerce.number().positive('القيمة مطلوبة') })
export const paymentSchema = z.object({ receivableId: required('الاستحقاق'), amount: z.coerce.number().positive('مبلغ الدفع يجب أن يكون أكبر من صفر'), paymentDate: required('تاريخ الدفع') })
export const expenseSchema = z.object({ propertyId: required('العقار'), description: required('البيان'), amount: z.coerce.number().positive('المبلغ يجب أن يكون أكبر من صفر') })
export const maintenanceSchema = z.object({ unitId: required('الوحدة'), title: required('عنوان الطلب'), estimatedCost: z.coerce.number().nonnegative() })
export const settlementSchema = z.object({ ownerId: required('المالك'), grossCollections: z.coerce.number().nonnegative(), transferAmount: z.coerce.number().nonnegative() })
export const attachmentSchema = z.object({ name: required('اسم الملف'), category: required('فئة المرفق'), relatedEntityType: required('نوع السجل المرتبط'), relatedEntityId: required('السجل المرتبط'), mimeType: z.string().optional(), size: z.coerce.number().nonnegative().optional() })
export const maintenanceApprovalSchema = z.object({ maintenanceRequestId: required('طلب الصيانة'), ownerId: required('المالك'), status: z.enum(['pending', 'approved', 'rejected']), notes: z.string().max(2000).optional() })
export const paymentReversalSchema = z.object({ paymentId: required('الدفعة'), reason: z.string().min(5, 'سبب عكس الدفعة مطلوب') })
export const reminderSchema = z.object({ title: required('عنوان التذكير'), dueDate: required('تاريخ الاستحقاق'), reminderDate: required('تاريخ التذكير'), type: z.enum(['rent_due', 'contract_expiry', 'maintenance', 'custom']) })
export const documentTemplateSchema = z.object({ name: required('اسم القالب'), category: required('فئة القالب'), bodyHtml: required('محتوى القالب'), isActive: z.boolean() })
export const communicationLogSchema = z.object({ relatedEntityType: required('نوع السجل'), relatedEntityId: required('السجل'), channel: z.enum(['email', 'sms', 'whatsapp', 'system']), subject: required('عنوان الرسالة'), body: required('محتوى الرسالة') })
