'use client'

import Link from 'next/link'
import { useState } from 'react'
import { AttachmentUploader, type LocalAttachment } from '@/components/shared/attachment-uploader'
import { expenses, leases, managementContracts, owners, payments, properties, settlements, tenants, units } from '@/mocks/data'

const tabs = ['نظرة عامة', 'العقارات والوحدات', 'المستأجرون والعقود', 'الدفعات', 'المصروفات', 'التسويات', 'المرفقات'] as const
type Tab = typeof tabs[number]
const money = (amount: number) => `${new Intl.NumberFormat('ar-SA').format(amount)} ر.س`

export function OwnerDetailsPage({ id }: { id: string }) {
  const [tab, setTab] = useState<Tab>('نظرة عامة')
  const [attachments, setAttachments] = useState<LocalAttachment[]>([])
  const owner = owners.find((item) => item.id === id)
  if (!owner) return <div className="content">المالك غير موجود.</div>
  const ownerProperties = properties.filter((item) => item.ownerId === id)
  const propertyIds = new Set(ownerProperties.map((item) => item.id))
  const ownerUnits = units.filter((item) => propertyIds.has(item.propertyId))
  const unitIds = new Set(ownerUnits.map((item) => item.id))
  const ownerLeases = leases.filter((item) => unitIds.has(item.unitId))
  const tenantIds = new Set(ownerLeases.map((item) => item.tenantId))
  const ownerTenants = tenants.filter((item) => tenantIds.has(item.id))
  const ownerPayments = payments.filter((item) => unitIds.has(item.unitId))
  const ownerExpenses = expenses.filter((item) => propertyIds.has(item.propertyId))
  const activeLeases = ownerLeases.filter((item) => item.status === 'active')
  const annualRent = activeLeases.reduce((sum, item) => sum + item.annualRent, 0)
  const collected = ownerPayments.filter((item) => item.status === 'confirmed').reduce((sum, item) => sum + item.amount, 0)
  const outstanding = activeLeases.flatMap((lease) => lease.installments).reduce((sum, installment) => sum + installment.amount, 0) - collected
  const settlement = settlements.find((item) => item.ownerId === id)
  const content: Record<Tab, React.ReactNode> = {
    'نظرة عامة': <><section className="owner-portfolio-snapshot"><div><span>إيجارات سنوية نشطة</span><b>{money(annualRent)}</b></div><div><span>محصلات مؤكدة</span><b>{money(collected)}</b></div><div><span>متبقي من العقود النشطة</span><b>{money(Math.max(0, outstanding))}</b></div><div><span>إشغال الوحدات</span><b>{ownerUnits.filter((unit) => unit.status === 'occupied').length} / {ownerUnits.length}</b></div></section><section className="card portfolio-explorer"><div className="card-heading"><div><h2>العقارات تحت إدارة المالك</h2><p>افتح العقار للوصول إلى وحداته ومستأجريه وإيجاراته ودفعاته.</p></div></div>{ownerProperties.map((property) => { const propertyUnits = units.filter((unit) => unit.propertyId === property.id); const leasesForProperty = activeLeases.filter((lease) => lease.propertyId === property.id); return <Link className="portfolio-property-link" key={property.id} href={`/properties/${property.id}`}><div><b>{property.propertyName}</b><span>{property.city} · {property.propertyType}</span></div><div><small>الوحدات</small><strong>{propertyUnits.length}</strong></div><div><small>المستأجرون</small><strong>{new Set(leasesForProperty.map((lease) => lease.tenantId)).size}</strong></div><div><small>الإيجار السنوي</small><strong>{money(leasesForProperty.reduce((sum, lease) => sum + lease.annualRent, 0))}</strong></div><span className="portfolio-open">فتح الملف ←</span></Link>})}</section><div className="owner-info-grid"><section className="owner-info-card"><header><span>هو</span><div><h2>بيانات المالك</h2><p>بيانات الهوية والتواصل المعتمدة</p></div></header><dl><div><dt>رقم الهوية</dt><dd>{owner.nationalIdOrIqama}</dd></div><div><dt>الجوال</dt><dd dir="ltr">{owner.mobilePrimary}</dd></div><div><dt>البريد الإلكتروني</dt><dd>{owner.email ?? 'غير مسجل'}</dd></div><div><dt>العنوان</dt><dd>{owner.city}{owner.district ? `، ${owner.district}` : ''}</dd></div></dl></section><section className="owner-info-card bank-info-card"><header><span>بن</span><div><h2>الحساب البنكي</h2><p>بيانات التحويل المعتمدة للمالك</p></div></header><dl><div><dt>اسم البنك</dt><dd>{owner.bankAccount.bankName}</dd></div><div><dt>صاحب الحساب</dt><dd>{owner.bankAccount.accountHolderName}</dd></div><div className="iban-row"><dt>رقم الآيبان</dt><dd dir="ltr">{owner.bankAccount.iban}</dd></div></dl></section></div></>,
    'العقارات والوحدات': <section className="card"><h2>عقارات المالك ووحداتها</h2>{ownerProperties.map((property) => { const propertyUnits = units.filter((unit) => unit.propertyId === property.id); const propertyLeases = activeLeases.filter((lease) => lease.propertyId === property.id); return <div className="summary-row" key={property.id}><div><b>{property.propertyName}</b><span>{propertyUnits.length} وحدات · {propertyUnits.filter((unit) => unit.status === 'occupied').length} مؤجرة · {new Set(propertyLeases.map((lease) => lease.tenantId)).size} مستأجرين · إيجار سنوي {money(propertyLeases.reduce((sum, lease) => sum + lease.annualRent, 0))}</span></div><Link className="cancel-button" href={`/properties/${property.id}`}>عرض العقار</Link></div> })}</section>,
    'المستأجرون والعقود': <section className="card"><h2>المستأجرون وعقودهم</h2>{ownerTenants.map((tenant) => { const contracts = ownerLeases.filter((lease) => lease.tenantId === tenant.id); return <div className="summary-row" key={tenant.id}><div><b>{tenant.fullName}</b><span>{tenant.mobilePrimary} · {contracts.map((item) => item.internalContractNumber).join('، ')}</span></div><Link className="cancel-button" href={`/tenants/${tenant.id}`}>ملف المستأجر</Link></div> })}{!ownerTenants.length && <p>لا يوجد مستأجرون مرتبطون بعقارات هذا المالك حاليًا.</p>}</section>,
    الدفعات: <section className="card"><h2>دفعات مستأجري المالك</h2>{ownerPayments.map((payment) => <div className="summary-row" key={payment.id}><div><b>{payment.paymentNumber}</b><span>{payment.paymentDate} · {tenants.find((item) => item.id === payment.tenantId)?.fullName ?? '—'}</span></div><b>{money(payment.amount)}</b></div>)}</section>,
    المصروفات: <section className="card"><h2>مصروفات العقارات</h2>{ownerExpenses.map((expense) => <div className="summary-row" key={expense.id}><div><b>{expense.description}</b><span>{expense.category} · {expense.expenseDate}</span></div><b>{money(expense.amount)}</b></div>)}</section>,
    التسويات: <section className="owner-settlement-card"><header><div><span>الملخص المالي</span><h2>تسوية المالك الحالية</h2><p>{settlement ? `${settlement.settlementNumber} · ${settlement.status === 'confirmed' ? 'تسوية معتمدة' : 'مسودة للمراجعة'}` : 'لا توجد تسوية مفتوحة حالياً'}</p></div><div className="settlement-balance"><span>المتبقي للمالك</span><b>{money(settlement?.remainingBalance ?? 0)}</b></div></header><div className="settlement-flow"><div className="settlement-income"><span>إجمالي المحصلات</span><b>{money(settlement?.grossCollections ?? 0)}</b><small>دفعات المستأجرين المؤكدة</small></div><i>−</i><div><span>أتعاب الإدارة</span><b>{money(settlement?.managementFees ?? 0)}</b><small>مقابل خدمات الإدارة</small></div><i>−</i><div><span>مصروفات المالك</span><b>{money(settlement?.ownerChargeableExpenses ?? 0)}</b><small>مصروفات محمّلة على المالك</small></div><i>=</i><div className="settlement-net"><span>صافي المستحق</span><b>{money(settlement?.netDueToOwner ?? 0)}</b><small>قبل التحويلات</small></div></div>{settlement && <Link className="cancel-button settlement-detail-link" href={`/owner-settlements/${settlement.id}`}>عرض تفاصيل التسوية</Link>}</section>,
    المرفقات: <section className="card"><h2>مرفقات المالك وعقود الإدارة</h2><AttachmentUploader value={attachments} onChange={setAttachments} entityType="owner" entityId={id} category="ملف المالك" /></section>,
  }
  return <div className="content owner-profile"><div className="module-title"><div><span className="overline">ملف المالك الشامل</span><h1>{owner.fullName}</h1><p>{owner.ownerCode} · {owner.mobilePrimary} · {owner.city}</p></div><div className="page-actions"><Link className="cancel-button" href={`/owners/${id}/edit`}>تعديل البيانات</Link><Link className="add-button" href="/owner-settlements/new">تسجيل تحويل</Link></div></div><div className="stats"><article className="stat"><span>العقارات</span><strong>{ownerProperties.length}</strong></article><article className="stat"><span>الوحدات</span><strong>{ownerUnits.length}</strong></article><article className="stat"><span>المستأجرون النشطون</span><strong>{ownerTenants.length}</strong></article><article className="stat"><span>الإيجارات السنوية</span><strong>{money(annualRent)}</strong></article></div><div className="detail-tabs">{tabs.map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div>{content[tab]}<section className="owner-management-contracts"><header><div><span>العقود النشطة</span><h2>عقود الإدارة</h2></div><b>{managementContracts.filter((item) => item.ownerId === id).length}</b></header>{managementContracts.filter((item) => item.ownerId === id).map((contract) => <article key={contract.id}><div className="contract-number"><span>رقم العقد</span><b>{contract.contractNumber}</b></div><div><span>مدة الإدارة</span><b>{contract.startDate} <i>←</i> {contract.endDate}</b></div><div><span>رسوم الإدارة</span><b>{contract.managementFeePercentage}% <small>من التحصيل</small></b></div><div className="contract-status"><i /> {contract.status === 'active' ? 'نشط' : contract.status}</div></article>)}{!managementContracts.some((item) => item.ownerId === id) && <p className="empty-contracts">لا يوجد عقد إدارة مسجل لهذا المالك.</p>}</section></div>
}
