'use client'

import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { HttpError } from '@/lib/api/http'
import { createOwnerBankAccount, getOwner, getOwnerPortfolio, type Owner, type OwnerPortfolio } from './api'

export function OwnerDetailsPage({ id }: { id: string }) {
  const [owner, setOwner] = useState<Owner>(); const [portfolio, setPortfolio] = useState<OwnerPortfolio>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [showBankForm, setShowBankForm] = useState(false); const [saving, setSaving] = useState(false)
  const reload = () => Promise.all([getOwner(id), getOwnerPortfolio(id)]).then(([currentOwner, currentPortfolio]) => { setOwner(currentOwner); setPortfolio(currentPortfolio) }).catch(() => setError('تعذر تحميل ملف المالك.')).finally(() => setLoading(false))
  useEffect(() => { let active = true; void Promise.all([getOwner(id), getOwnerPortfolio(id)]).then(([result, resultPortfolio]) => { if (active) { setOwner(result); setPortfolio(resultPortfolio) } }).catch(() => { if (active) setError('تعذر تحميل ملف المالك.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [id])
  async function saveBankAccount(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setError(''); try { await createOwnerBankAccount(id, { bankName: String(data.get('bankName')), iban: String(data.get('iban')).replaceAll(' ', '').toUpperCase(), accountHolderName: String(data.get('accountHolderName')), isDefault: Boolean(data.get('isDefault')) }); setShowBankForm(false); reload() } catch (reason) { setError(reason instanceof HttpError ? reason.message : 'تعذر حفظ الحساب البنكي.') } finally { setSaving(false) } }
  if (loading) return <div className="content">جارٍ تحميل ملف المالك…</div>
  if (!owner) return <div className="content" role="alert">{error || 'المالك غير موجود.'}</div>
  return <div className="content owner-profile"><div className="module-title"><div><span className="overline">ملف المالك</span><h1>{owner.fullName}</h1><p>{owner.ownerCode} · {owner.mobilePrimary} · {owner.city}</p></div><div className="page-actions"><Link className="cancel-button" href={`/owners/${id}/edit`}>تعديل البيانات</Link><Link className="add-button" href="/owner-settlements/new">إنشاء تسوية</Link></div></div><section className="owner-info-grid"><article className="owner-info-card"><h2>بيانات المالك</h2><dl><div><dt>رقم الهوية</dt><dd>{owner.nationalIdOrIqama}</dd></div><div><dt>الجوال</dt><dd dir="ltr">{owner.mobilePrimary}</dd></div><div><dt>البريد</dt><dd>{owner.email || 'غير مسجل'}</dd></div><div><dt>العنوان</dt><dd>{owner.city}{owner.district ? `، ${owner.district}` : ''}</dd></div></dl></article><article className="owner-info-card bank-info-card"><div className="card-heading"><h2>الحسابات البنكية</h2><button className="cancel-button" disabled={saving} onClick={() => setShowBankForm((open) => !open)}>إضافة حساب</button></div>{owner.bankAccounts?.length ? <dl>{owner.bankAccounts.map(account => <div key={account.id}><dt>{account.bankName}{account.isDefault ? ' (افتراضي)' : ''}</dt><dd dir="ltr">{account.iban}</dd></div>)}</dl> : <p>لا يوجد حساب بنكي محفوظ.</p>}{showBankForm && <form className="entity-form" onSubmit={saveBankAccount}><label>اسم البنك<input required name="bankName" disabled={saving} /></label><label>صاحب الحساب<input required name="accountHolderName" disabled={saving} /></label><label>IBAN<input required name="iban" dir="ltr" pattern="[A-Za-z]{2}[0-9A-Za-z]{13,32}" disabled={saving} /></label><label><input name="isDefault" type="checkbox" disabled={saving} /> الحساب الافتراضي</label><button className="add-button" disabled={saving} type="submit">{saving ? 'جارٍ الحفظ…' : 'حفظ الحساب'}</button></form>}</article></section>{error && <p className="error-message" role="alert">{error}</p>}<section className="card"><h2>محفظة المالك</h2>{portfolio ? <><p>العقارات: {portfolio.summary.propertiesCount} · المساحات: {portfolio.summary.spacesCount} · الإيجار السنوي المتوقع: {portfolio.summary.expectedAnnualRent} ر.س</p>{portfolio.properties.length ? portfolio.properties.map(property => <div className="summary-row" key={property.id}><div><b>{property.propertyName}</b><span>{property.propertyCode} · {property.city} · {property.spacesCount} مساحات</span></div><small>{property.expectedAnnualRent} ر.س</small></div>) : <p>لا توجد عقارات مرتبطة بهذا المالك.</p>}</> : <p>جارٍ تحميل المحفظة…</p>}</section></div>
}
